### ISSUE TITLE
add stealth fingerprint

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2258] opened 2023-11-09 12:16 UTC
its important thing to stay anonymous
some sites like google,.. can detect with fingerprint

please add methods like change webgl and vendor and... to stay anonymous and undetectable
there is a tools that can change it but also making browser detectable
https://github.com/diprajpatra/selenium-stealth

if you dont know how, can you give information or advice to us?

**Comment by mdmintz** [comment] 2023-11-09 20:24
This is a **duplicate** of all your other recent **WebGL** questions:
* https://github.com/seleniumbase/SeleniumBase/issues/2031
* https://github.com/seleniumbase/SeleniumBase/issues/2040
* https://github.com/seleniumbase/SeleniumBase/issues/2048
* https://github.com/seleniumbase/SeleniumBase/issues/2168

It's also a duplicate of other people's recent WebGL questions (eg. https://github.com/seleniumbase/SeleniumBase/discussions/2248)

Any issues you have with https://github.com/diprajpatra/selenium-stealth should be addressed in their repo. Not this one.

SeleniumBase UC Mode is about preventing discrimination against bots. (Eg. If a human can visit a website, then a bot should be able to do the same.) To do that, a bot's fingerprint is configured to resemble that of a human using that exact same web browser. It's not about being able to set that fingerprint to whatever you want it to be. (Can't fake some things.)

Your high number of duplicate tickets asking for the same thing over and over again is certainly grounds for getting blocked, especially since https://github.com/seleniumbase/SeleniumBase/issues/2249 was just created two days ago for preventing duplicate tickets such as this one.

**Closed by mdmintz** 2023-11-09 20:24 UTC
Labels: duplicate, question
