### ISSUE TITLE
Continuous Driver download problem

### ISSUE THREAD

**Issue by mvx20** [seleniumbase/SeleniumBase#2805] opened 2024-05-25 02:36 UTC
Every time I run it it downloads the driver as in the image, does it have to do this every time?
<img width="1017" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/88004617/99ee1baa-440f-41be-a930-fe71a8f2d1c8">

**Comment by mdmintz** [comment] 2024-05-25 03:25
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2665#discussioncomment-9021973

The Chromium Team changed the download location of drivers, and SeleniumBase was updated to use the newer location over three months ago in https://github.com/seleniumbase/SeleniumBase/issues/2519

Upgrade to a newer version of SeleniumBase.

**Closed by mdmintz** 2024-05-25 03:25 UTC
Labels: duplicate

**Comment by mvx20** [comment] 2024-05-25 20:58
thanx solved.
