### ISSUE TITLE
Do we have the plan to add the function that record testing script execution as a video for playback?

### ISSUE THREAD

**Issue by dashng** [seleniumbase/SeleniumBase#2900] opened 2024-07-03 13:47 UTC
Dear @mdmintz,

Compare to Cypress, do we have the plan to add the feature that record the testing exectuion steps and saved it as a video for playing back.

As we run the script in linux with --headless, which without UI, so we expect to view the execution steps when meet any issues and not just a screenshot.

Thanks

**Comment by mdmintz** [comment] 2024-07-03 13:59
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/642#issuecomment-666353300.

Use an existing tool with SeleniumBase such as Zalenium for recording videos:
https://opensource.zalando.com/zalenium/
It works like a Selenium Grid.
See https://seleniumbase.io/seleniumbase/utilities/selenium_grid/ReadMe/ for instructions on using SeleniumBase to connect to a Selenium Grid.

**Closed by mdmintz** 2024-07-03 13:59 UTC
Labels: duplicate, question
