### ISSUE TITLE
How to change the proxy settings of an active browser in the middle of a test?

### ISSUE THREAD

**Issue by gouravkumar99** [seleniumbase/SeleniumBase#2100] opened 2023-09-12 16:20 UTC
Thanks @mdmintz for the support, but I am not using wire. I am using the Driver() option as follows:

`proxy_d = f"{self.PROXY_USER}:{self.PROXY_PASSWORD}@{self.PROXYURL}:{self.proxy_randomport}"
driver = Driver(uc=True,user_data_dir=user_data_dir, multi_proxy=True, proxy=proxy_d)`

i want to change new proxy in running browser.

_Originally posted by @gouravkumar99 in https://github.com/seleniumbase/SeleniumBase/issues/1807#issuecomment-1716028657_

**Comment by mdmintz** [comment] 2023-09-12 16:47
@gouravkumar99 - Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1807#issuecomment-1472800048

 The only way to change the proxy of an active browser in the middle of a test is with Wire Mode enabled (``--wire``) and using the `set_wire_proxy()` method:

```python
self.set_wire_proxy("SERVER:PORT")
self.set_wire_proxy("socks5://SERVER:PORT")
self.set_wire_proxy("USERNAME:PASSWORD@SERVER:PORT")
```

#### (Note that Wire Mode cannot be used together with UC Mode.)

**Closed by mdmintz** 2023-09-12 16:47 UTC
Labels: duplicate, question, UC Mode
