### ISSUE TITLE
Problem with UC Mode (from chromedriver / uc_driver)

### ISSUE THREAD

**Issue by thomvas** [seleniumbase/SeleniumBase#3204] opened 2024-10-19 13:15 UTC
Hi,

my code is this:

```
from seleniumbase import Driver

driver = Driver(uc=True, headless2=True)

url = "https://www.amazon.com/"

driver.get(url)
```

I have SeleniumBase 4.31.6. I use MacOS 15.0 Sequoia with Intel and Chrome 130.0.6723.59.

This code sometimes gives me this error.

![2024-10-19_15-02](https://github.com/user-attachments/assets/30f64e8b-97a2-4bb0-9369-6a969a7cd597)

The error is also on MacOS with Apple Silicon and rosetta installed.

I've found that deleting uc=True solves the problem, so the following code works.

```
from seleniumbase import Driver

driver = Driver(headless2=True)

url = "https://www.amazon.com/"

driver.get(url)
```

Could it be a bug? How can I use UC Mode on MacOS without problems?

Thanks :)

**UPDATE:

i updated my chrome on windows and i have same problem also on Windows**

**Comment by mdmintz** [comment] 2024-10-19 19:42
Probably a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/3205#issuecomment-2424100386

**Comment by schamen** [comment] 2024-10-21 09:16
hello
win10, python12.7, installed chrome v129 and webdriver v129. 
trying to start example raw_cf.py but always get Traceback (most recent call last):
  File "D:\python\SeleniumBase-master\SeleniumBase-master\seleniumbase\core\browser_launcher.py", line 4460, in get_local_driver
    driver = undetected.Chrome(
             ^^^^^^^^^^^^^^^^^^
  File "D:\python\SeleniumBase-master\SeleniumBase-master\seleniumbase\undetected\__init__.py", line 311, in __init__
    super().__init__(options=options, service=service_)
  File "C:\Users\SAM\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\SAM\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\SAM\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__ ...

i don't understand what i must to do to resolve such errors.
can you help me?

**Closed** 2024-10-21 17:46 UTC
Labels: duplicate, workaround exists, UC Mode
