### ISSUE TITLE
RuntimeError: You cannot reuse the ChromeOptions object

### ISSUE THREAD

**Issue by ttraxxrepo** [seleniumbase/SeleniumBase#3027] opened 2024-08-15 16:34 UTC
Getting the following error when trying to use user_data_dir.

The first run of the code (before user_data_dir is created) works, but then once its created and we try to use it, I get the error

```
Traceback (most recent call last):
  File "//main.py", line 67, in <module>
    Scrape().run()
  File "/bots/scrape.py", line 17, in run
    with SB(uc=True, user_data_dir=self.user_data_dir, incognito=True, test=True, slow=True, demo_sleep=3) as sb:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/plugins/sb_manager.py", line 986, in SB
    sb.setUp()
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/fixtures/base_case.py", line 14916, in setUp
    self.driver = self.get_new_driver(
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/fixtures/base_case.py", line 4101, in get_new_driver
    new_driver = browser_launcher.get_driver(
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/core/browser_launcher.py", line 2339, in get_driver
    return get_local_driver(
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/core/browser_launcher.py", line 4304, in get_local_driver
    driver = undetected.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/undetected/__init__.py", line 136, in __init__
    raise RuntimeError("You cannot reuse the ChromeOptions object")
RuntimeError: You cannot reuse the ChromeOptions object
```

where `self.user_data_dir = "user_data_dir/scrape"` and `user_data_dir` is a blank folder I created, which I can see being written to successfully on the first run

Code is simply:
```Python
with SB(uc=True, incognito=True, user_data_dir=self.user_data_dir, test=True, slow=True, demo_sleep=3) as sb:
    self.login(sb)
```

Interestingly enough when I run the code locally (virtualenv on MacBook) I do not get this error, however when running the code in docker I do. Pems on docker are all 755 and the path is mounted to host (where I see files being written on the first execution of code)
```yml
    volumes:
      - ${APPDATA_DIR}/Scraper/saved_cookies:/saved_cookies
      - ${APPDATA_DIR}/Scraper/user_data_dir:/user_data_dir
```

**Comment by mdmintz** [comment] 2024-08-15 16:48
Duplicate of https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/555 and https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1342.

And I mentioned in earlier SeleniumBase tickets that UC Mode does not support Docker.
If you have an issue with Docker configuration when using UC Mode, you're on your own.

Since it works fine outside Docker, this is a non-issue.

**Closed by mdmintz** 2024-08-15 16:48 UTC
Labels: duplicate, incorrect usage, UC Mode

**Comment by AdilMughal2126** [comment] 2024-08-15 20:53
I am facing the same issue on ec2 instance using Ubuntu. When I gave proxy options it stop working and throw the same error. I don't what is wrong.

**Comment by ightingale** [comment] 2024-10-03 12:47
with SB(uc=True, test=True, xvfb=True) as sb:


             ^^^^^^^^^^^^^^^^^^
  File "/home/dev/.cache/pypoetry/virtualenvs/botozel-fiTi4r-N-py3.11/lib/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 137, in __init__
    raise RuntimeError("You cannot reuse the ChromeOptions object")
RuntimeError: You cannot reuse the ChromeOptions object


I am encountering the same error, and I suspect that SeleniumBase might be the cause. I’m not using Docker, nor have I made any specific setup configurations aside from what I mentioned above.

What should I do to get rid of this error? I tried setting a random user_data_dir as a parameter, but that didn’t help.

I initially wanted to explore the issue on my own, but I found the SeleniumBase source code a bit difficult to follow. It seems there could be some room for improvement in terms of PEP compliance, which made debugging a little more challenging than anticipated. It's impressive that the project has gained 5,000 stars on GitHub—clearly, it has a lot of value for the community despite the complexities in the code.

**Comment by mdmintz** [comment] 2024-10-03 13:02
@ightingale Were you spinning up multiple UC Mode browsers at the same time? And if so, did you follow the instructions for activating the built-in thread-locking system to prevent port conflicts?

**Comment by ightingale** [comment] 2024-10-03 13:21
> @ightingale Were you spinning up multiple UC Mode browsers at the same time? And if so, did you follow the instructions for activating the built-in thread-locking system to prevent port conflicts?


In my project, there is a feature that allows multiple browsers to open simultaneously, but this error occurs even during the first browser launch. I tested this after a full system reboot.
I couldn't find the instructions you're referring to. Could you please share a link to them? I would greatly appreciate it.

**Comment by mdmintz** [comment] 2024-10-03 13:45
This can occur when spinning up multiple browsers at the same time if you didn't activate the built-in thread-locking system with `-n` in `sys.argv`. (See the multithreading section in the [UC Mode Docs](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md).) When not activated, two or more processes could become tied to the same `remote-debugging-port` number (probably `9222`), which results in conflicts because two processes can't control the same Chrome browser at the same time. If you do not wish to use the built-in thread-locking system, you can also avoid this issue by spacing out your browser launches. Once launched, you can have multiple browsers running at the same time.

**Comment by daftping** [comment] 2025-06-24 02:10
I was facing exactly the same issue.
This PR fixes the issue
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1505/files
You can just run before each run to replicate the fix.
`rm user_data_dir/Singleton*`
