### ISSUE TITLE
Access denied error(403 forbidden) when when using seleniumbase

### ISSUE THREAD

**Issue by pauljohnySN** [seleniumbase/SeleniumBase#2399] opened 2023-12-30 17:41 UTC
I tried using the  `sb.driver.uc_click(selector) `but after multiple tries webpage again comes as forbidden 

```
with SB(uc=True) as sb:
    sb.driver.uc_open_with_reconnect(
        "https://www.capterra.com/360-degree-feedback-software/",
        reconnect_time="breakpoint",
    )
    sb.driver.uc_click('/html/body/div[2]/div/div[3]/div[1]/div[2]/div/div[1]/nav/a[9]/i')
```

And how to change the proxy settings?

_Originally posted by @pauljohnySN in https://github.com/seleniumbase/SeleniumBase/issues/2398#issuecomment-1872571099_

**Comment by mdmintz** [comment] 2023-12-30 17:52
Duplicate of:
* https://github.com/seleniumbase/SeleniumBase/issues/2398

**Closed by mdmintz** 2023-12-30 17:52 UTC
Labels: duplicate, UC Mode
