### ISSUE TITLE
Feature Request: Allow `uc.click()` to accept `WebElement` element objects directly

### ISSUE THREAD

**Issue by cdchris12** [seleniumbase/SeleniumBase#2809] opened 2024-05-27 15:50 UTC
As a user of SeleniumBase, I would like the `uc.click()` function to accept not only xpaths and css selectors, but also WebElement objects as well. This functionality would simplify coding by not needing to reference the location of an element twice, especially in cases where an element's location needs to be searched for or obtained via another function.

**Comment by mdmintz** [comment] 2024-05-29 02:55
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2229#discussioncomment-7658873

`element.uc_click()` already exists when using UC Mode:

https://github.com/seleniumbase/SeleniumBase/blob/7d9d5c5203e3d93bdfc50f9d113c88791e9ba26c/seleniumbase/undetected/webelement.py#L5

It's not recommended though, because using it can lead to `ElementClickInterceptedException` or `StaleElementReferenceException`, which is prevented by using a regular CSS Selector that's fed into a JavaScript call for the UC click functionality of the regular `driver.uc_click(selector)` method.

**Closed by mdmintz** 2024-05-29 02:55 UTC
Labels: duplicate, workaround exists, UC Mode
