### ISSUE TITLE
UC Mode issues with chromedriver 130 / Chrome 130

### ISSUE THREAD

**Issue by Magic4k** [seleniumbase/SeleniumBase#3205] opened 2024-10-19 14:02 UTC
everything was fine and working good after the chrome driver update the uc mode makes driver don't recognize any element of web page instead when removing uc=True 
it works fine and detects all elements on the page so it means the driver update made something like conflict please help

**Comment by Magic4k** [comment] 2024-10-19 16:07
> Hi, are you on MacOS? I have similar problem on MacOS, [here i opened a ticket](https://github.com/seleniumbase/SeleniumBase/issues/3204)

no I'm windows OS but I think the solution is to back 2 old versions of chrome driver and chrome browser so that uc mode works fine

**Comment by mdmintz** [comment] 2024-10-19 17:28
Try setting driver_version="129"

That workaround should work until a more permanent solution becomes available. I’m figuring out how to properly patch all the driver changes that appeared in 130.

**Comment by Magic4k** [comment] 2024-10-19 17:39
thank you in advance but I tried to add driver_version="129" with Driver format and still when adding uc=True 
it doesn't work and when removing uc it works fine

**Comment by Magic4k** [comment] 2024-10-19 19:57
yes It worked now thank you mintz you are a gem anyway I appreciate your work so much ♥

**Comment by Zezima126** [comment] 2024-10-21 17:38
it seems to open two windows after `driver.get(url)`. This is breaking the code for some websites. 
What worked for me is closing the second window 
```
handles = driver.window_handles
if len(driver.window_handles) != 1:
        for handle in handles[1:]:
            driver.switch_to.window(window_name=handle)
            driver.close()
```

Not a very elegant workaround , but maybe helpful if driver_version="129" isnt doing the trick.

**Comment by JasonCrowe** [comment] 2024-10-23 01:06
I am experiencing an issue that I think is related. 
I have a script that uses the Nopecha extension to autosolve reCaptcha.

Part of my script will change to the captcha iframe and check that it's been solved. 

The script occasionally opens the same content in a new tab. The only problem with this is that the original tab will keep auto-solving the captcha after the solution resets, using up my credits.

**Comment by mdmintz** [comment] 2024-10-23 01:47
The issue is related to the new structure of the `user-data-dir` in Chrome 130. If stopping the WebDriver service on a newly-created `user-data-dir`, then there could be intermittent problems when starting the WebDriver service back up. When this issue occurs, WebDriver incorrectly believes that the URL of the page is a Chrome extension (because the URL starts with `chrome-extension://`, which happens because the built-in Chrome extensions are one of the first items to appear in newly-created user-data-dirs). The fix is to create the `user-data-dir` in advance, and then tell the UC Mode browser to use that at start-up.

**Comment by JasonCrowe** [comment] 2024-10-23 03:47
I tried that, and it caused problems. The browser would open, and then nothing else happens.

When you say to create the user-dir in advance, do you mean create the folder, or to use another script that will create the user-dir, then have my script use this dir?

**Comment by mdmintz** [comment] 2024-10-23 04:08
> I tried that, and it caused problems. The browser would open, and then nothing else happens.
> 
> When you say to create the user-dir in advance, do you mean create the folder, or to use another script that will create the user-dir, then have my script use this dir?

@JasonCrowe The entire folder structure with data files must be there in advance. (Starting in Chrome 130) That means another script must run in advance.

**Comment by JasonCrowe** [comment] 2024-10-23 04:33
I tried using a profile folder created a few weeks ago, but it didn't work. Is there anything else I can try?

**Comment by mdmintz** [comment] 2024-10-23 04:58
> I tried using a profile folder created a few weeks ago, but it didn't work. Is there anything else I can try?

Wait for the next SeleniumBase release. Coming soon.

**Comment by Mersh-NI** [comment] 2024-10-23 08:10
Tell me why some pages of the site in SB UC mode load only
<body>
 <script src="audio.js"></script>
</body>

This happens after upgrading to Chrome 130

**Comment by kvvvotheOnnen** [comment] 2024-10-23 15:27
in some pages im gettin this response with the self.get_page_source()
<html><head></head><body>
  <script src="audio.js"></script><audio></audio>

</body></html>
i'm using the latest chrome version 130

**Comment by mdmintz** [comment] 2024-10-23 21:23
Fixed in `4.32.0` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.32.0

**Closed by mdmintz** 2024-10-23 21:23 UTC
Labels: workaround exists, UC Mode

**Comment by mdmintz** [comment] 2024-10-29 14:14
Upgrade to `4.32.5` (or newer if available). Details: https://github.com/seleniumbase/SeleniumBase/issues/3236

**Comment by NicoNicoNico123** [comment] 2024-11-07 05:25
> Tell me why some pages are being replaced with chrome-extension://neajdppkdcdipfabeoofebfddakdcjhd/audio.html in SB UC mode
> 
> This happens after upgrading to Chrome 130
> 
> The problem is described in [more detail here](https://stackoverflow.com/questions/79111414/scrapy-spider-using-seleniumbase-middleware-scraping-chrome-extension-urls-tha/79118306#79118306)

me too, but it seem fix issue
