### ISSUE TITLE
Not able to run on ARM based Ubuntu

### ISSUE THREAD

**Issue by atjtest** [seleniumbase/SeleniumBase#2741] opened 2024-05-02 17:27 UTC
I tried to run SeleniumBase on a ARM based Ubuntu installation, it complained can't find a driver for chrome.

The script I tested is https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_simple_login.py

Error messages:
...
selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64

....
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

Is there any alternative way to make it work?

Thanks.

**Comment by mdmintz** [comment] 2024-05-02 17:32
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2619#discussioncomment-8833670: 

The `Unsupported platform/architecture combination: linux/aarch64` has some info here:
https://groups.google.com/g/selenium-users/c/MRfrR7pu_8I
with an answer here: https://groups.google.com/g/selenium-users/c/MRfrR7pu_8I/m/F9U3eMC0AAAJ

Use the SeleniumBase [Dockerfile](https://github.com/seleniumbase/SeleniumBase/blob/master/Dockerfile) to run SeleniumBase on any Linux system that supports Docker.

**Closed by mdmintz** 2024-05-02 17:32 UTC
Labels: duplicate, question
