### ISSUE TITLE
Chrome Browser Freezing and Blank Screen Issue

### ISSUE THREAD

**Issue by zscrape** [seleniumbase/SeleniumBase#3025] opened 2024-08-14 21:41 UTC
Hi @mdmintz, thanks for all your hard work on this project!

I'm encountering an issue where Chrome suddenly freezes, becomes unresponsive, and then displays a blank screen (see screenshot: <img width="1410" alt="Screen Shot 2024-08-14 at 2 32 18 PM" src="https://github.com/user-attachments/assets/d4ec3123-4ab1-4a0e-afa1-4f80f926f892">). At this point, I have to force quit. This typically occurs 1-2 minutes into running my script, and I'm having trouble identifying the cause.

Is there any specific log data I can collect to help troubleshoot this issue?

I'm running macOS 12.7.4 and SeleniumBase 4.29.9. I haven't had the chance to test other combinations of macOS and SeleniumBase versions yet.

**Comment by mdmintz** [comment] 2024-08-14 21:51
This isn't enough information for me to reproduce the issue. I haven't seen this...
I'll need to see some code for what you're doing, and stack traces to help debug.

I'll close this for now, but we can reopen this later if I have the information I need.

**Closed by mdmintz** 2024-08-14 21:51 UTC
Labels: more info needed, can't reproduce

**Comment by zscrape** [comment] 2024-08-15 02:13
OK I narrowed it down to the exact version that breaks for me: 4.11.4
With 4.11.3 I do not see the issue. Not sure if its related to having an intel mac. I will work on getting example code to you. The site requires login and I cannot share it. I will try and study whats happening in the browser when the hang occurs.

https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.11.4

**Comment by zscrape** [comment] 2024-08-15 02:13
What is the best way to collect a stacktrace?

**Comment by mdmintz** [comment] 2024-08-15 02:18
A stack trace should automatically appear on error. If you're using an Intel Mac, you may need to have Rosetta installed. Even if you can't share code, I need to see the options you were using, eg. headless mode.

**Comment by zscrape** [comment] 2024-08-15 02:28
No problem, maybe this will help?

`import json
from urllib.parse import urlparse
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from logger_config import logger
import config


def domain_to_cookie_domain(domain):
    parts = domain.split('.')
    if len(parts) > 2:
       return '.' + '.'.join(parts[-2:])
    return domain


def login(sb):
    try:
       # Try to load saved cookies
       try:
          with open("cookies.json", "r") as f:
             cookies = json.load(f)
       except FileNotFoundError:
          logger.info("No saved cookies found.")
          cookies = None

       # Navigate to the login page
       sb.get("https://www.example.com/login")

       if cookies:
          for cookie in cookies:
             if 'domain' in cookie:
                parsed_domain = urlparse(sb.current_url).netloc
                cookie['domain'] = domain_to_cookie_domain(parsed_domain)
             if 'expiry' in cookie:
                del cookie['expiry']
             try:
                sb.add_cookie(cookie)
             except Exception as e:
                logger.error(f"Error adding cookie: {e}")

          # Refresh the page to apply cookies
          sb.refresh()

       # Check if already logged in
       try:
          WebDriverWait(sb, 10).until(EC.visibility_of_element_located((By.CSS_SELECTOR, "#profile")))
          logger.info("Already logged in using saved cookies!")
          return True
       except TimeoutException:
          logger.info("Not logged in. Performing manual login...")

       # Perform manual login
       WebDriverWait(sb, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#EnteredUserName")))
       sb.type("#UserName", "user")
       sb.type("#Password", "password")
       sb.click("#LoginButton")

       # Check if login was successful
       try:
          WebDriverWait(sb, 10).until(EC.visibility_of_element_located((By.CSS_SELECTOR, "#profile-container")))
          logger.info("Login successful!")
          # Save new cookies
          cookies = sb.get_cookies()
          with open("cookies.json", "w") as f:
             json.dump(cookies, f)
          return True
       except TimeoutException:
          logger.error("Login failed!")
          return False

    except Exception as e:
       logger.error(f"An error occurred during login: {e}")
       return False`

What happens is it goes to the login page then loads the cookies and refreshes. User is now logged in but about 20-30 seconds later something about the page and this specific seleniumbase version causes the driver to hang and become unresponsive. I can usually cause it to happen faster by manually interacting with it.

RE Rosetta, do you mean install Rosetta 1? It seems Rosetta 2 is for running intel based apps on mac silicon macs and Rosetta 1 is very old.

**Comment by zscrape** [comment] 2024-08-15 02:42
Interestingly I also get the cloudflare challenge and it is not able to bypass it

**Comment by mdmintz** [comment] 2024-08-15 02:54
Actually, Rosetta might only be needed for ARM Macs to run old Intel code.

You shouldn't be using `WebDriverWait` at all because SeleniumBase has its own waiting system that may conflict with `WebDriverWait` or `expected_conditions`. See the examples for reference.

Also see the UC Mode docs for proper CAPTCHA bypass: [SeleniumBase/help_docs/uc_mode.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md)

You also may need to use the `SB()` format instead of the `Driver()` format.

**Comment by ttraxxrepo** [comment] 2024-08-15 04:48
@mdmintz sounds identical to issue is I was referencing [here](https://github.com/seleniumbase/SeleniumBase/issues/3012)... after further testing I realized the proxy actually had nothing to do with it. 2020 MacBook Pro Intel was freezing, no stack trace or logs. Then running on my other newer MacBook (2022) everything worked fine

**Comment by zscrape** [comment] 2024-08-15 04:53
Thanks @ttraxxrepo , that’s very helpful to hear! I am looking to upgrade my trash can man pro to Apple silicon very soon.  I will see if I still have the issue on the new machine.

**Comment by ttraxxrepo** [comment] 2024-08-15 13:01
@zscrape I recall getting some temporary relief by using a fresh venv and restarting the entire machine, have a feeling it was a memory leak issue but not 100%

**Comment by zscrape** [comment] 2024-08-15 23:59
I reproduced on another intel macbook 2017

**Comment by ttraxxrepo** [comment] 2024-08-16 02:35
@zscrape are you using `save_cookies()` or `load_cookies()` in your code by any chance? Commenting it out seems to have made the freezes stop, although I'm not sure if its just coincidental
