### ISSUE TITLE
RuntimeError: You cannot reuse the ChromeOptions object 

### ISSUE THREAD

**Issue by ightingale** [seleniumbase/SeleniumBase#3174] opened 2024-10-03 13:06 UTC
`with SB(uc=True, test=True, xvfb=True) as sb:`

```
  File "/home/dev/.cache/pypoetry/virtualenvs/project-fiTi4r-N-py3.11/lib/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 137, in __init__
    raise RuntimeError("You cannot reuse the ChromeOptions object")
RuntimeError: You cannot reuse the ChromeOptions object
```

os: ubuntu
seleniumbase = "^4.30.8"
Google Chrome 127.0.6533.99
ChromeDriver 127.0.6533.72 (9755e24ca85aa18ffa16c743f660a3d914902775-refs/branch-heads/6533@{#1760})

I am encountering the error mentioned above, and I suspect the issue is related to SeleniumBase, as I am not using Docker and all the launch configurations are specified above.

Previously, I was using undetected-chromedriver and never encountered this problem.

What do I need to do to fix this error? I tried setting a random user_data_dir as a parameter, but that didn't help. How can I modify the ChromeOptions created by SeleniumBase to prevent this issue?

I initially wanted to explore the issue on my own, but I found the SeleniumBase source code a bit difficult to follow. It seems there could be some room for improvement in terms of PEP compliance, which made debugging a little more challenging than anticipated. It's impressive that the project has gained 5,000 stars on GitHub—clearly, it has a lot of value for the community despite the complexities in the code.

What other information would be useful from my side to help identify the cause of this issue?

**Comment by mdmintz** [comment] 2024-10-03 13:42
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/3027.

This can occur when spinning up multiple browsers at the same time if you didn't activate the built-in thread-locking system with `-n` in `sys.argv`. (See the multithreading section in the [UC Mode Docs](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md).) When not activated, two or more processes could become tied to the same `remote-debugging-port` number (probably `9222`), which results in conflicts because two processes can't control the same Chrome browser at the same time. If you do not wish to use the built-in thread-locking system, you can also avoid this issue by spacing out your browser launches. Once launched, you can have multiple browsers running at the same time.

**Closed by mdmintz** 2024-10-03 13:42 UTC
Labels: duplicate, UC Mode

**Comment by ightingale** [comment] 2024-10-03 15:18
I tried adding `-n` to `sys.argv`, but it didn’t help, and I am getting the same error. The solution you suggested doesn’t work, most likely because in my code the browsers are launched from different processes, not from a single one.

The final solution was:

`with SB(uc=True, test=True, xvfb=True, user_data_dir=str(user_data_dir), port=str(get_free_port())) as sb:`

So far, this works without any errors. Thank you for your help!
