### ISSUE TITLE
find_elements InvalidArgumentException                  

### ISSUE THREAD

**Issue by assomy** [seleniumbase/SeleniumBase#3016] opened 2024-08-12 11:00 UTC
Hi,
i have this code works 
posts = driver.find_elements("//article")
for post in posts:
         #user = post.find_element(By.XPATH, ".//h3//a").text  #works fine in selenium 
        user= post.find_element( ".//h3//a").text # give  InvalidArgumentException on  SeleniumBase
        url= post.find_element(".//h3//a").get_attribute('href')   # give  InvalidArgumentException  SeleniumBase
How i can port it to SeleniumBase?
thanks

**Comment by mdmintz** [comment] 2024-08-12 12:01
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2916#issuecomment-2213994224 and https://github.com/seleniumbase/SeleniumBase/discussions/2895#discussioncomment-9930193.

WebElements use the original Selenium API, where the `by` arg comes before the `selector`.
Your call would be: `post.find_element("xpath", ".//h3//a")`

**Closed by mdmintz** 2024-08-12 12:01 UTC
Labels: duplicate, question
