### ISSUE TITLE
Downloading the uc_driver

### ISSUE THREAD

**Issue by a1malgorithm** [seleniumbase/SeleniumBase#3103] opened 2024-09-06 18:57 UTC
Let's use a simple example code

```
from seleniumbase import Driver

driver = Driver(uc=True)
url = "https://gitlab.com/users/sign_in"
driver.uc_open_with_reconnect(url, 4)
driver.uc_gui_click_captcha()
driver.quit()
```

The driver keep downloading everytime i use the the code i want it to download the driver once

**Comment by mdmintz** [comment] 2024-09-06 19:11
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/3073 and https://github.com/seleniumbase/SeleniumBase/issues/2046. (Assuming you are using `PyInstaller`, because otherwise I can't reproduce this.)

----

`chromedriver` / `uc_driver` is only downloaded if it doesn't already exist in the `seleniumbase/drivers` folder.
It looks like you've configured `pyinstaller` to generate a new folder every time it runs. (`seleniumbase` doesn't have control over that.) That means it'll keep downloading the driver unless you configure `PyInstaller` to reuse the folder.

If you can't change `PyInstaller` configuration, you can hide those install messages by adding this:

```python
from seleniumbase.config import settings
settings.HIDE_DRIVER_DOWNLOADS = True
```

`PyInstaller` is an external project, so you'll have to figure out how to configure it properly.

**Closed by mdmintz** 2024-09-06 19:11 UTC
Labels: duplicate, UC Mode
