### ISSUE TITLE
Multithreading bot using SeleniumBase

### ISSUE THREAD

**Issue by fashionprivate** [seleniumbase/SeleniumBase#2356] opened 2023-12-10 22:47 UTC
Hello,

I'm implementing a multithreading python bot to scrape a Twitter account.
I implemented scraping using Threads (threading.Thread). In my case I want create about 20 threads that scrape a specific Twitter page account.
The logic I implemented works but the CPU goes to 100% after a few threads (about 10).
I think I'm doing the thread management wrong. How can I optimize the algorithm? Should I use py-test?

```python
from seleniumbase import SB

def start_twitter(args):
    accounts = 20
    threads = []
    
    for index, account in enumerate(accounts):
        # ... ...
        thread = MyThread()
        threads.append(thread)
        thread.start()
    
    for t in threads:
        try:
            t.join()
        except Exception as e:
            pass

class MyThread(threading.Thread):
    def run(self):
        with SB(uc=True, extension_dir="temp/old-twitter-layout-2023/", headless2=True) as sb:
            sb.driver.uc_open("https://www.twitter.com")
            # scraping
```

The ```start_twitter(args)``` method is called from an ```async def``` method.

Thanks in advance

**Comment by mdmintz** [comment] 2023-12-11 00:58
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2006#issuecomment-1679789785

**Closed by mdmintz** 2023-12-11 00:58 UTC
Labels: duplicate, UC Mode
