### ISSUE TITLE
No such file or directory "\\seleniumwire\\ca.crt"

### ISSUE THREAD

**Issue by ShogoDev0212** [seleniumbase/SeleniumBase#2340] opened 2023-12-05 13:04 UTC
# Environment
python : 3.9.1
seleniumbase：4.19.0

# To Reploduce
I've created a Python exe file using PyInstaller.
When I run it on the computer it was coded on it works. 
However when I run it on another PC I get this error.

```
from seleniumbase import SB

with SB(wire=True) as sb:
    sb.open("https://google.com")
    input("Please Enter...")
```

Error
```
No such file or directory: 'C:\\Users\\***\\AppData\\Local\\Temp\\_MEI180322\\seleniumwire\\ca.crt'
```

# Expected behavior
I want it to work fine.
Please let me know if there are any possible remedies or ideas that may help solve this issue. Thank you.

**Comment by mdmintz** [comment] 2023-12-05 13:28
Duplicate of https://github.com/wkeeling/selenium-wire/issues/402#issuecomment-1059038086

**Closed by mdmintz** 2023-12-05 13:28 UTC
Labels: duplicate, external
