### ISSUE TITLE
UC Browser, can't continue at CF checkbox

### ISSUE THREAD

**Issue by JimKarvo** [seleniumbase/SeleniumBase#2626] opened 2024-03-20 22:11 UTC
I have an script that running 24/7, no problem till some hours ago.

I updated the SeleniumBase just in case, but seems that there is an update on Cloudflare that detects the UC.

I tryied the example code, with no luck.
```
"""SB Manager using UC Mode for evading bot-detection."""
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://gitlab.com/users/sign_in"
    sb.driver.uc_open_with_reconnect(url, 3)
    if not sb.is_text_visible("Username", '[for="user_login"]'):
        sb.driver.uc_open_with_reconnect(url, 4)
    sb.assert_text("Username", '[for="user_login"]', timeout=3)
    sb.assert_element('label[for="user_login"]')
    sb.highlight('button:contains("Sign in")')
    sb.highlight('h1:contains("GitLab.com")')
    sb.post_message("SeleniumBase wasn't detected", duration=4)
```

My working code till some hours ago:
```
with SB(uc=True) as driver:
      while True:
            if driver.is_element_visible('iframe[src*="challenge"]'):
                loguru.logger.error("have the iframe element.")
                with driver.frame_switch('iframe[src*="challenge"]'):
                    try:
                        driver.click("span.mark")
                    except:
                        pass
                    driver.sleep(1.5)
            else:
                break
            _loop_cnt += 1
            driver.sleep(1.5)
            if _loop_cnt > 20:
                exit()
```

Maybe somehow I can help with the debugging?

**Comment by mdmintz** [comment] 2024-03-20 22:35
This script is working for me at getting past the initial CAPTCHA screen:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://gitlab.com/users/sign_in"
    sb.driver.uc_open_with_reconnect(url, 3)
    if not sb.is_text_visible("Username", '[for="user_login"]'):
        sb.driver.uc_open_with_reconnect(url, 4)
    sb.assert_text("Username", '[for="user_login"]', timeout=3)
    sb.assert_element('label[for="user_login"]')
    sb.highlight('button:contains("Sign in")')
    sb.highlight('h1:contains("GitLab.com")')
    sb.post_message("SeleniumBase wasn't detected", duration=4)
```

Is it not working for you?

**Comment by oculunto** [comment] 2024-03-20 22:45
I just came to comment the same, it is detecting the selenium/seleniumbase click and uc_click somehow, because disconnecting the driver and clicking manually works

**Comment by mdmintz** [comment] 2024-03-20 22:51
Looks like Cloudflare made a change today.

It's good news that the page-load bypasses still work. That means there will be a way to make the clicks work again too.

Here's a Game of Thrones quote response:

![currently_at_work](https://github.com/seleniumbase/SeleniumBase/assets/6788579/4a185a24-58ee-4aed-981c-65d5781c3bab)

https://github.com/seleniumbase/SeleniumBase/assets/6788579/9481c7ed-995e-461a-a323-fda917f73879

**Comment by JimKarvo** [comment] 2024-03-20 23:17
> It's good news that the page-load bypasses still work. That means there will be a way to make the clicks work again too.

Are there any example code for this?

**Comment by mdmintz** [comment] 2024-03-20 23:20
@JimKarvo Of the page-load bypass? That's just: https://github.com/seleniumbase/SeleniumBase/issues/2626#issuecomment-2010771069

**Comment by JimKarvo** [comment] 2024-03-20 23:22
> @JimKarvo Of the page-load bypass? That's just: [#2626 (comment)](https://github.com/seleniumbase/SeleniumBase/issues/2626#issuecomment-2010771069)

Also this is not working for me (code running on Ubuntu server, no GUI)

**Comment by mdmintz** [comment] 2024-03-20 23:27
@JimKarvo Working for me. Show me some code where it doesn't work for you.

For headless ubuntu, make sure you're using:

```python
from seleniumbase import SB

with SB(uc=True, headed=True, xvfb=True) as sb:
    sb.driver.uc_open_with_reconnect(URL, 4)
    # ...
```

**Comment by JimKarvo** [comment] 2024-03-21 00:19
I made this code, for testing:

The first part (to win the CF without click) not worked.

I tryied also to click the box, with no luck (the box is clicked, but I get again and again the same page...)

```
"""SB Manager using UC Mode for evading bot-detection."""
from seleniumbase import SB

with SB(uc=True, test=True, headed=True, xvfb=True) as sb:
    url = "https://gitlab.com/users/sign_in"
    sb.driver.uc_open_with_reconnect(url, 4)

    #This part of code completelly fails!

    sb.driver.save_screenshot("test-pre.png")
    if not sb.is_text_visible("Username", '[for="user_login"]'):
        sb.driver.uc_open_with_reconnect(url, 4)
    sb.driver.save_screenshot("test-after.png")


    # Trying to click the span, using headed and xvfb
    _loop_cnt = 0
    while True:
        if sb.driver.is_element_visible('iframe[src*="challenge"]'):
            sb.driver.save_screenshot("test-middle.png")
            with sb.frame_switch('iframe[src*="challenge"]'):
                try:
                    print("trying to click...")
                    sb.driver.click("label.ctp-checkbox-label")
                    print("clicked.")
                except Exception as e:
                    print(e)
                    exit()
                sb.driver.sleep(1.5)
        else:
            if sb.driver.get_title() != "Just a moment...":
                print("Finnaly, we won the CF?")
                print(sb.driver.get_title())
                break
            else:
                sb.driver.save_screenshot("test-middle.png")
                print(sb.driver.get_title())
        _loop_cnt += 1
        sb.driver.sleep(5)
        if _loop_cnt > 20:
            exit()

    sb.driver.save_screenshot("test-middle.png")
    sb.post_message("SeleniumBase wasn't detected", duration=4)
 ```

**Comment by mdmintz** [comment] 2024-03-21 00:27
I'm aware of the click getting detected after the latest CF changes.
But the part with just getting through without doing anything is working correctly for me.

**Comment by JimKarvo** [comment] 2024-03-21 00:29
> I'm aware of the click getting detected after the latest CF changes. But the part with just getting through without doing anything is working correctly for me.

Even at ubuntu server? (No monitor, no Desktop Enviroment)

**Comment by mdmintz** [comment] 2024-03-21 00:33
@JimKarvo What's the output of `sb.get_user_agent()` for you? I think that may be your issue.

**Comment by JimKarvo** [comment] 2024-03-21 00:38
@mdmintz I got this `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

**Comment by mdmintz** [comment] 2024-03-21 00:50
I think I'm close to a solution for macOS and Windows, but I don't have a headed Linux machine to test with. If the User Agent of a Desktop Linux Machine is different from headless Linux, then I think changing the UA could help. Someone will have to check for me.

**Comment by ertugrulcakici** [comment] 2024-03-21 01:52
I'm using the same library, and I believe the issue is more than just clicking the checkbox. The problem also involves Cloudflare redirecting me back to the protection page, even when I click manually. I managed to bypass this by opening a new window and waiting there for a few seconds. Afterwards, I click the checkbox, try again until it accepts and return to my original page. This method allowed me to successfully bypass on my original page. I hope this helps other bot creators

**Comment by mdmintz** [comment] 2024-03-21 03:04
As Qyburn would say about the newest version of CF's CAPTCHA checkbox:
It's "Powerful, but not invincible".

![powerful_but_not_invincible](https://github.com/seleniumbase/SeleniumBase/assets/6788579/8a9d03b1-4997-4343-8fe9-e1f5289a3735)

Now, "If you'll kindly pull that lever" after `pip install pyautogui` with the latest version of SeleniumBase:

```python
import pyautogui
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    sb.driver.uc_open_with_reconnect("https://seleniumbase.io/apps/turnstile")
    sb.send_keys("html", "\t")
    sb.driver.disconnect()
    pyautogui.press(" ")
    sb.sleep(1)
    sb.driver.connect()
    sb.assert_element("img#captcha-success", timeout=3)
    sb.set_messenger_theme(location="top_left")
    sb.post_message("SeleniumBase wasn't detected", duration=3)
```

<img width="1392" alt="Screenshot 2024-03-20 at 11 00 44 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/f02e55c6-8d16-4df1-b8f9-43d8933d6c30">

Tested on macOS. You may have to enable permissions for the terminal to send keyboard actions.

**Comment by ruany** [comment] 2024-03-21 11:04
Thanks, here's my clickless headless Linux solution which uses xdotool on xvfb instead of pyautogui:

bash:
``` bash
workaround() {
    xvfbs=$(ps aux|grep '[X]vfb'|grep -Eo ':[0-9]+$')
    for xvfb in $xvfbs; do
        DISPLAY="$xvfb" xdotool key space
    done
}

base_delay=8
offset=6

for i in 1 2 3 4; do
    (sleep $[base_delay + (offset*i)]; workaround) &
done
```

python:
``` python
PAGE_DELAY = 4.5
PAGE_TIMEOUT = 42

URL = sys.argv[1]

def is_challenge(src):
    return "Ray ID:" in src or "needs to review the security of your connection" in src or "Verifying you are human." in src or "Verify you are human" in src or "Checking if the site connection" in src or "Why am I seeing this page" in src

with SB(uc=True, headed=True, xvfb=True) as sb:
    driver = sb.driver
    try:
        driver.set_page_load_timeout(PAGE_TIMEOUT)
        driver.uc_open_with_reconnect(URL, PAGE_DELAY)

        for x in range(1,8):
            sb.sleep(1)
            src = driver.execute_script("return document.body.innerHTML;")
            if 'src' not in vars() or src == "":
                sb.sleep(3)
                continue
            if is_challenge(src):
                if sb.is_element_visible('iframe[src*="challenge"]'):
                    #with sb.frame_switch('iframe[src*="challenge"]'):
                    #    sb.click("span.mark")
                    sb.send_keys("html", "\t")
                    driver.disconnect()
                    sb.sleep(6)
                    driver.connect()
                    if (x % 3) == 0:
                        driver.uc_open_with_reconnect(URL, PAGE_DELAY)
                continue
            break
        print(src)
    finally:
        driver.quit()
```
Using default UA, checkbox is no longer a threat.

**Comment by JimKarvo** [comment] 2024-03-21 12:30
@ruany how to call the bash_script? I am at "\t", and it seems that I have focus on checkbox.

**Comment by ruany** [comment] 2024-03-21 12:44
@JimKarvo Simply run the python script after the bash script.

It can also run in parallel as a separate process, but I have it set up like this:

``` bash
# ... workaround ...
cd $(dirname "$0")
export PYTHONPATH="$PWD/pyvenv/lib/python3.9/site-packages"

source pyvenv/bin/activate && ./http-get.py "$@"
```

**Comment by JimKarvo** [comment] 2024-03-21 15:06
@ruany seems that can't work on headless systems (ubuntu server 22.04), or maybe you have a different setup

**Comment by vyanezz** [comment] 2024-03-21 16:51
For me, with Linux on a remote machine CF detects and clicking on the box does not work. Everything was working before this.

**Comment by mdmintz** [comment] 2024-03-21 17:13
Made some calls. Figured it out. A pure `selenium` solution without `pyautogui` should be ready later today.

![bill_nye](https://github.com/seleniumbase/SeleniumBase/assets/6788579/d5eb26a7-e752-4ffb-b21a-08dc304020f0)

https://github.com/seleniumbase/SeleniumBase/assets/6788579/21c5ff49-2a70-44d4-9037-450459534b53

----

Also, some of you still haven't Starred the repo on GitHub: ⭐⭐⭐⭐⭐

More stars = faster release. https://github.com/seleniumbase/SeleniumBase/stargazers

**Comment by mdmintz** [comment] 2024-03-21 21:48
Resolved in `4.24.12` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.24.12

![good_scientist](https://github.com/seleniumbase/SeleniumBase/assets/6788579/a5ac28be-5055-4b97-bc96-01bcda4ab44f)

https://github.com/seleniumbase/SeleniumBase/assets/6788579/20e0703b-fdb7-43ec-9f69-2ad793c08895

----

Upgrade, and try the updated examples.

**Closed** 2024-03-21 22:17 UTC
Labels: workaround exists, feature or fix already exists, UC Mode, Fun

**Comment by iPhaco** [comment] 2024-03-21 23:01
Hello,
Thank you for the project and the work you do. CF works correctly without proxy, but it doesn't work with proxy, maybe they detect the extension.
Regards

**Comment by mdmintz** [comment] 2024-03-21 23:05
I tested with some non-auth proxies and UC Mode worked successfully.
It could be that you used a proxy that was already banned as bot-traffic.

**Comment by mdmintz** [comment] 2024-03-21 23:51
In case anyone missed the announcement, UC Mode is fixed in `4.24.12`.

Examples to try:

* [examples/raw_uc_mode.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py)
* [examples/raw_turnstile.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py)
* [examples/raw_form_turnstile.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py)
* [examples/raw_ahrefs.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_ahrefs.py)
* [examples/raw_pixelscan.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_pixelscan.py)

**Comment by praveenyadav3011** [comment] 2024-10-26 05:57
i am trying from more then 24 hours, uc working fine, but sometime i need to click on check box, check box clicking not working on below website:
https://fastwin.trade/LR?LG&C=

does cloudflare implement in new way?

**Comment by praveenyadav3011** [comment] 2024-10-26 06:10
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py

not working now, please update.
