### ISSUE TITLE
change proxy when the IP is blocked

### ISSUE THREAD

**Issue by gouravkumar99** [seleniumbase/SeleniumBase#2096] opened 2023-09-12 08:17 UTC
how to change proxy when the IP is blocked without restarting the driver?

**Comment by mdmintz** [comment] 2023-09-12 13:48
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1807#issuecomment-1472800048.
See the link above to change proxy settings in the middle of a test during Wire Mode.

**Closed by mdmintz** 2023-09-12 13:48 UTC
Labels: duplicate, question
