### ISSUE TITLE
add seleniumwire option

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2032] opened 2023-08-25 21:01 UTC
i wanna add this option to seleniumwire
```
seleniumwire_options = {}
seleniumwire_options['exclude_hosts'] = ['website.com']
```

and my code:
```
with SB(uc=True, wire=True) as sb:
...
```

**Comment by mdmintz** [comment] 2023-08-25 21:09
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1774#issuecomment-1444399269

There's ``--uc`` mode, and there's ``--wire`` mode, but the two can't be used together due to unresolved issues with ``selenium-wire``: https://github.com/wkeeling/selenium-wire/search?q=undetected&type=issues

But the good news is that you don't need the wire integration anymore because SeleniumBase now has ``--uc-cdp`` mode, which can collect ALL the same data that ``--wire`` mode collected.

Here's an example that uses it: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py

**Closed by mdmintz** 2023-08-25 21:09 UTC
Labels: duplicate

**Comment by YOTYTeaM** [comment] 2023-08-25 21:20
thank you, i saw that

so how can i exclude host with that?

**Comment by mdmintz** [comment] 2023-08-25 21:41
@YOTYTeaM See https://github.com/seleniumbase/SeleniumBase/issues/1776#issuecomment-1445130601

**Comment by YOTYTeaM** [comment] 2023-08-25 22:34
> @YOTYTeaM See [#1776 (comment)](https://github.com/seleniumbase/SeleniumBase/issues/1776#issuecomment-1445130601)

thank you
actually seleniumwire and undetected_selenium not working for me
just seleniumbase works for me.

i got an idea, i think thats gonna work

```
from mitmproxy import http, options
from mitmproxy.tools.main import mitmdump

class ExcludeHosts:
    def __init__(self, excluded_hosts):
        self.excluded_hosts = ['google.com',  'website.com']

    def request(self, flow: http.HTTPFlow) -> None:
        for host in self.excluded_hosts:
            if host in flow.request.host:
                flow.kill()

if __name__ == "__main__":
    opts = options.Options(listen_host='127.0.0.1', listen_port=8080)
    mitmdump(opts, scripts=[__file__])
```
here we need to run this file and use the proxy in seleniumBase (http 127.0.0.1:8080)
