### ISSUE TITLE
Is it possible to use seleniumbase to run in a docker containerized chrome session in python. Using selenium it is possible, but for running into cloudflare requires use of seleniumbase.

### ISSUE THREAD

**Issue by purpleZeahorze** [seleniumbase/SeleniumBase#3070] opened 2024-08-29 00:09 UTC
This is the docker commands to create a containerized chrome session:

docker pull selenium/standalone-chrome
docker run --rm -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome

python code:
#import selenium
from selenium import webdriver
#create driver with remote connection to localhost
driver = webdriver.Remote('http://localhost:4444/wd/hub', webdriver.ChromeOptions()))
driver.set_window_size(1280, 1024)
driver.get('https://www.google.com')
print(driver.page_source.encode("utf-8"))
driver.quit()

I am trying to find documentation that will allow me to do something like:

import seleniumbase as SB

    with SB(uc=True) as sb:
        sb.uc_open_with_reconnect(url, 2)
                # Wait for the element to be present
        try:
            sb.wait_for_element_visible('div.ds-dex-table.ds-dex-table-top', timeout=2)
            
            
            
 But I am unable to get this to run in the docker containerized chrome session, I cannot find any parameter to specify a remote connection.

**Comment by mdmintz** [comment] 2024-08-29 00:58
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/3057#discussioncomment-10461674 and https://github.com/seleniumbase/SeleniumBase/issues/2675#issuecomment-2047434434:
"UC Mode is not compatible with the Grid / Remote WebDriver".

There's lots of documentation on using SeleniumBase with a Selenium Grid / Remote WebDriver: ([SeleniumBase/seleniumbase/utilities/selenium_grid/ReadMe.md](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/utilities/selenium_grid/ReadMe.md) and [SeleniumBase/examples/capabilities](https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities))
but **you can't use UC Mode with the Grid**.

The original undetected-chromedriver doesn't support the Grid / Remote WebDriver either:
https://github.com/search?q=repo%3Aultrafunkamsterdam%2Fundetected-chromedriver+grid&type=issues

The Grid / Remote WebDriver is a problem for UC Mode because while the Grid controls chromedriver, the Grid does not have the root control that is needed. UC Mode requires raw control for modifying a local chromedriver (renamed to uc_driver), as well as for disconnecting the driver from Chrome, and reconnecting to it a short time later. It's also not possible to control `pyautogui` remotely from the Grid. (Note that `pyautogui` is required for multiple UC Mode actions.)

And as mentioned in https://github.com/seleniumbase/SeleniumBase/issues/2979#issuecomment-2261272353:
"Note that UC Mode isn't fully compatible with Docker, as Docker leaves a unique fingerprint that can make UC Mode detectable by CAPTCHAs. (No issues with regular Linux.)"
Regular SeleniumBase works fine with Docker. Just not UC Mode.

**Closed by mdmintz** 2024-08-29 00:58 UTC
Labels: duplicate, question, UC Mode
