### ISSUE TITLE
Interrupting the recorder from outside the terminal

### ISSUE THREAD

**Issue by Roboflex30** [seleniumbase/SeleniumBase#2753] opened 2024-05-06 08:14 UTC
Hi @mdmintz, I am creating a product using Seleniumbase library to record and playback my browser actions. The only problem I am facing is that after I run the command **sbase mkrec my_project.py --url=wikipedia.org** and it starts the recorder, the only way to stop is to type 'c' and press "Enter" in the command line. Once I start the recording at the user end, the user cannot go to the terminal to press 'c' and hit 'enter' as the users don't have the access to the terminal. So I want to kill/interrupt/add breakpoint from outside the terminal either by hitting a shortcut key or calling another script, or I can make changes to the installed seleniumbase script through the python package. Please enlighten me with the solution as it has become a bottleneck in the project.

**Comment by mdmintz** [comment] 2024-05-06 19:29
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1075#issuecomment-971744681

**Closed by mdmintz** 2024-05-06 19:29 UTC
Labels: duplicate
