### ISSUE TITLE
BUG: Seleniumbase PermissionError: [Errno 13] Permission denied afther update

### ISSUE THREAD

**Issue by boludoz** [seleniumbase/SeleniumBase#2570] opened 2024-03-06 21:39 UTC
```
Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.94/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
[ERROR] Error al guardar captura de pantalla
[ERROR] Error desconocido durante la ejecucion
    - Traceback (most recent call last):
    -   File "C:\Cp\bot_garena\bot_garena\bot_garena.py", line 764, in bot_garena
    -     instance = next(iterator, None)
    -                ^^^^^^^^^^^^^^^^^^^^
    -   File "C:\Cp\bot_garena\bot_garena\bot_garena.py", line 686, in nav_code
    -     raise e
    -   File "C:\Cp\bot_garena\bot_garena\bot_garena.py", line 571, in nav_code
    -     driver_handle = WebDriver()
    -                     ^^^^^^^^^^^
    -   File "C:\Cp\bot_garena\bot_garena\bot_garena.py", line 452, in __init__
    -     self.driver = Driver(**params_driver)
    -                   ^^^^^^^^^^^^^^^^^^^^^^^
    -   File "C:\Python312\Lib\site-packages\seleniumbase\plugins\driver_manager.py", line 488, in Driver
    -     driver = browser_launcher.get_driver(
    -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    -   File "C:\Python312\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 1612, in get_driver
    -     return get_local_driver(
    -            ^^^^^^^^^^^^^^^^^
    -   File "C:\Python312\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 3510, in get_local_driver
    -     driver = undetected.Chrome(
    -              ^^^^^^^^^^^^^^^^^^
    -   File "C:\Python312\Lib\site-packages\seleniumbase\undetected\__init__.py", line 130, in __init__
    -     self.patcher.auto()
    -   File "C:\Python312\Lib\site-packages\seleniumbase\undetected\patcher.py", line 87, in auto
    -     return self.patch_exe()
    -            ^^^^^^^^^^^^^^^^
    -   File "C:\Python312\Lib\site-packages\seleniumbase\undetected\patcher.py", line 211, in patch_exe
    -     with io.open(self.executable_path, "r+b") as fh:
    -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    - PermissionError: [Errno 13] Permission denied: 'C:\\Python312\\Lib\\site-packages\\seleniumbase\\drivers\\uc_driver.exe'
```

**Comment by boludoz** [comment] 2024-03-06 21:42
And it would also be good if the file was saved with a hash or a reference to the original so that it is not downloaded again all the time.

**Comment by mdmintz** [comment] 2024-03-06 21:54
Looks like a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1926#issuecomment-1609938541

You'll need to make sure SeleniumBase can access and modify `uc_driver` so that the driver can be patched.

Probably the easiest way to do that would be to use a virtual environment.
(See [help_docs/virtualenv_instructions.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/virtualenv_instructions.md) to learn about creating and using virtual environments.)

**Closed by mdmintz** 2024-03-06 21:54 UTC
Labels: duplicate, UC Mode

**Comment by boludoz** [comment] 2024-03-06 21:57
This didn't happen before, therefore I consider it a bug, don't be afraid of making mistakes.

**Comment by mdmintz** [comment] 2024-03-06 22:12
The base algorithm of the SeleniumBase Chromedriver Patcher is unchanged from the `undetected-chromedriver` version:

https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/0aa5fbe252370b4cb2b95526add445392cad27ba/undetected_chromedriver/patcher.py#L347

If you have an issue with the Patcher, mention that in the `undetected-chromedriver` repo.
