### ISSUE TITLE
[Enhancement Request] Add Option to Configure "downloaded_files/" Path

### ISSUE THREAD

**Issue by DRVR1** [seleniumbase/SeleniumBase#2479] opened 2024-02-09 22:09 UTC
Hello, i hope this message finds you well and thank you for mantaining SeleniumBase.

Currently, when a SeleniumBase program is packed into an executable file for Windows (in this case, pyInstaller standalone), and executed from a location with restricted permissions, such as an Read/Execute only location like `ProgramFiles`, the "downloaded_files/" folder cannot be created. This limitation leads to unexpected behaviors, such as the parameter `is_mobile=True` being ignored. 

Context code:
`from seleniumbase import Driver`
`driver = Driver(is_mobile=True)`

This can be solved by asking the user for admin privileges, then the folder can be created correctly, but in order to improve the user experience and keep the security that is provided by executing a program as a standard user, I kindly request the addition of an option to configure the "downloaded_files/" path. This feature would allow users to specify a custom path as needed, ensuring consistent and reliable behavior across different execution environments.

Thank you for considering my request. I believe this enhancement would greatly benefit the SeleniumBase community and improve the overall user experience when packing and installing SeleniumBase software.

**Comment by mdmintz** [comment] 2024-02-10 04:19
Hello, That folder needs to be created in the location where the script is invoked. If permissions are missing for creating a folder there, then you would run into the same issue if you tried changing the name of the folder that gets created. I'd set things up so that the script has permissions to create folders and files within the folder where the script is invoked.

----

Also duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2427

--------

SeleniumBase creates the ``downloaded_files`` folder in the working directory where ``pytest`` is invoked. Any click-initiated downloads will go there. It's also used for any special files needed. It also holds lock files to prevent issues with multi-threading. The folder resets at the start of every new ``pytest`` run so that past test runs don't interfere with new ones. The folder is hard-coded there to prevent issues. And since the folder is reset at the start of new ``pytest`` runs, you wouldn't want to use any other existing folders for it.

There are lots of built-in test methods that are specially made for that folder, such as:

```python
self.get_downloads_folder()

self.get_browser_downloads_folder()

self.get_path_of_downloaded_file(file)

self.is_downloaded_file_present(file)

self.delete_downloaded_file_if_present(file)
# Duplicates: self.delete_downloaded_file(file)

self.assert_downloaded_file(file)

self.get_downloaded_files(regex=None, browser=False)

self.get_data_from_downloaded_file(file, timeout=None, browser=False)

self.assert_data_in_downloaded_file(data, file, timeout=None, browser=False)
```

If you need files in a different folder, use Python ``os``, ``sys``, and ``shutil`` libraries for copying the files you need into a different folder after they get downloaded to the ``downloaded_files`` folder.

There's also a `pytest` command-line option to archive existing downloads instead of deleting them:
https://github.com/seleniumbase/SeleniumBase/blob/570910c6f6e079cddd00c23e826e202c6489f39e/README.md?plain=1#L673

(A copy of those downloads will go into a folder in the `archived_files/` folder at the end of the `pytest` run.)

**Closed by mdmintz** 2024-02-10 04:19 UTC
Labels: duplicate
