### ISSUE TITLE
Chrome is stuck with same IP when using a proxy.

### ISSUE THREAD

**Issue by mobti100** [seleniumbase/SeleniumBase#2617] opened 2024-03-17 02:20 UTC
```
Proxy and IP info from the session:
user:pass@5.178.6.85:12323
{'ip': '5.178.6.85', 'city': 'Lizy-sur-Ourcq', 'region': 'Île-de-France', 'country': 'FR', 'loc': '49.0245,3.0218', 'org': 'AS2914 NTT America, Inc.', 'postal': '77440', 'timezone': 'Europe/Paris', 'readme': 'https://ipinfo.io/missingauth'}

Proxy and IP info from chrome:
user:pass@5.178.6.85:12323
{
  "ip": "185.134.195.244",
  "city": "Saint-Denis",
  "region": "Île-de-France",
  "country": "FR",
  "loc": "48.9356,2.3539",
  "org": "AS6830 Liberty Global B.V.",
  "postal": "93200",
  "timezone": "Europe/Paris",
  "readme": "https://ipinfo.io/missingauth"
}
```
It does not change even when changing proxy providers, it's just stuck with that data.

```python
async def sign_in(username, password, proxy):
    try:
        with SB(uc=True, proxy=proxy) as sb:
            print(proxy)
            sb.driver.uc_open('http://example.com')
            sb.driver.type('#username', username)
            sb.driver.type('#password', password)
            sb.driver.click('#kc-login')
            standard_logger.info(f'Signed in as {username}')
            return sb.driver.get_cookies()
    except Exception:
        raise


async def create_session(account, proxy, timeout):
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}
    session = AsyncSession(
        impersonate='chrome119',
        timeout=timeout,
        headers=headers,
        proxies={'https': proxy}
    )
    response = await session.get('https://ipinfo.io/json')
    print(proxy)
    print(response.json())
    cookies = await sign_in(account['username'], account['password'], proxy)
    for cookie in cookies:
            session.cookies.set(cookie['name'], cookie['value'], domain=cookie['domain'])
    return session, account['username'], account['issuer'], account['id'], account['variant']

**Comment by mobti100** [comment] 2024-03-17 02:58
<img width="1685" alt="Screenshot 2024-03-17 at 02 57 00" src="https://github.com/seleniumbase/SeleniumBase/assets/137413814/5da3bb2d-92e1-4d9a-8de8-bf15362bd71f">

I also noticed that the driver uses one single proxy for all instances even though each driver is configured to use a different proxy

**Comment by mdmintz** [comment] 2024-03-17 03:38
You have to set `multi_proxy=True`:

https://github.com/seleniumbase/SeleniumBase/blob/e4abd8e8beec5a85b31fcddcbdfd231812af15c4/seleniumbase/plugins/sb_manager.py#L44

This feature has existed since April 2023 - https://github.com/seleniumbase/SeleniumBase/issues/1832

Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2101#issuecomment-1721093399

**Closed by mdmintz** 2024-03-17 03:38 UTC
Labels: duplicate, incorrect usage, UC Mode

**Comment by mobti100** [comment] 2024-03-17 03:42
Yes, I just fixed it and you replied. Also sometimes the challenge page  doesn't let me through and I have to manually click verify, any fix for that.

**Comment by mdmintz** [comment] 2024-03-17 03:49
Set a longer `reconnect_time` for `sb.driver.uc_open_with_reconnect(url, reconnect_time)`.
Has to be at least as long as the time it takes for the page to finish loading. Eg. [examples/raw_pixelscan.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_pixelscan.py)

**Comment by mobti100** [comment] 2024-03-17 03:54
I appreciate your help

**Comment by mobti100** [comment] 2024-03-17 10:35
I noticed when launching multiple instances asynchronously, a conflict occurs in how `proxy_ext_dir_n` folders are created.
I keep receiving for example proxy_ext_dir_2 already exists because all instances are attempting to create extension folders at the same time. Is there a way that I can custom rename those folder in SB so such conflict does not happen?

```python
def get_cookies(proxy, username, password):
    with SB(uc=True, proxy=proxy, multi_proxy=True) as sb:
        sb.driver.uc_open_with_reconnect('http://example.com/login', 5)
        sb.driver.type('#username', username)
        sb.driver.type('#password', password)
        sb.driver.click('#login')

        return sb.driver.get_cookies()

async def create_session(account, proxy, timeout):
    headers = {
        'User-Agent': ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
                       'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 '
                       'Safari/537.36')
    }
    session = AsyncSession(
        impersonate='chrome119',
        timeout=timeout,
        http_version=CurlHttpVersion.V2_0,
        headers=headers,
        proxies={'https': proxy}
    )

    loop = asyncio.get_running_loop()
    cookies = await loop.run_in_executor(custom_executor, get_cookies, proxy, account['username'], account['password'])
    for cookie in cookies:
        session.cookies.set(cookie['name'], cookie['value'], domain=cookie['domain'])

    return session, account['username'], account['issuer'], account['id'], account['variant']

**Comment by mdmintz** [comment] 2024-03-17 14:24
Multithreaded UC Mode: https://github.com/seleniumbase/SeleniumBase/issues/2006#issuecomment-1679789785
