### ISSUE TITLE
find_element function does not work on selenium web element

### ISSUE THREAD

**Issue by luey-punch** [seleniumbase/SeleniumBase#2916] opened 2024-07-08 08:42 UTC
```python
def find_buttons_with_review_ids(self, uniq_id):
    """
    Finds all buttons with both data-review-id and data-href attributes.
    """
    base_path = (
        f"{BASE_XPATH}div/div[1]/div/div/div[2]//button"
    )
    elements = self.find_elements(base_path)
    print(f"rev_elements {elements}")
    reviewers = []
    for element in elements:
        review_id = element.get_attribute("data-review-id")
        print(f"\nreview_id  {review_id}")
        if review_id:
            review_divs = element.find_element("//div")
            print(f"\nreview_divs  {review_divs}")
            review_spans = element.find_element("//span")
            print(f"\nreview_spans  {review_spans}")

    return reviewers
```

I get an error saying **invalid argument: invalid locator**
Adding the 'by' param returns **WebElement.find_elements() got multiple values for argument 'by'**

Even using `element.find_elements("//span","xpath")` still throws an error

**Comment by mdmintz** [comment] 2024-07-08 12:51
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2895#discussioncomment-9930193

**Closed by mdmintz** 2024-07-08 12:51 UTC
Labels: duplicate, incorrect usage
