### ISSUE TITLE
Seleniumbase often raises a KeyError: session id when executing some javascript commands

### ISSUE THREAD

**Issue by symonk** [seleniumbase/SeleniumBase#592] opened 2020-06-03 11:20 UTC
Often we see when executing tests in CI, the following:

```python
KeyError: 'sessionId'
```

When inspecting the stack during these incidents (varied/random when they occur) there is always one common trait, it is the execution of javascript.  See an example below:

```
product/pom/login_page.py:47: in login_as
    censored_data
product/pom/login_page.py:31: in decorated
    censored_data
product/pom/login_page.py:61: in __handle_login
    censored_data
product/pom/login_page.py:78: in accept_eula
    censored_data
product/pom/base_page.py:187: in click
    censored_data
venv/lib/python3.7/site-packages/seleniumbase/fixtures/base_case.py:158: in click
    self.wait_for_ready_state_complete()
venv/lib/python3.7/site-packages/seleniumbase/fixtures/base_case.py:1425: in wait_for_ready_state_complete
    is_ready = js_utils.wait_for_ready_state_complete(self.driver, timeout)
venv/lib/python3.7/site-packages/seleniumbase/fixtures/js_utils.py:27: in wait_for_ready_state_complete
    ready_state = driver.execute_script("return document.readyState")
venv/lib/python3.7/site-packages/selenium/webdriver/support/event_firing_webdriver.py:88: in execute_script
    return self._dispatch("execute_script", (script, self._driver), "execute_script", unwrapped_args)
venv/lib/python3.7/site-packages/selenium/webdriver/support/event_firing_webdriver.py:160: in _dispatch
    raise e
venv/lib/python3.7/site-packages/selenium/webdriver/support/event_firing_webdriver.py:157: in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py:636: in execute_script
    'args': converted_args})['value']
lib/plugins/stack_debugging_plugin.py:39: in execute
    response = self.command_executor.execute(driver_command, params)
venv/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py:369: in execute
    path = string.Template(command_info[1]).substitute(params)
/usr/lib/python3.7/string.py:132: in substitute
    return self.pattern.sub(convert, self.template)
```

Unfortunately its hard to create a 'recreatable' example, but we get around 1-2 keyerror session ID during a full CI run on pretty much every run, test varies massively.

This could also lie with selenium/grid/ etc, but I'd like to query your thoughts on it / what might be causing it.

has there been any changes regarding this stuff recently? (cant see any in release notes - I am currently rolling up dependency versions so it might be helped there, merely a question at this point).

**Comment by symonk** [comment] 2020-06-03 12:27
Also I monkeypatched selenium you retry on these failures but not much luck, if you are wondering about the plugin lines in the stack trace

**Comment by mdmintz** [comment] 2020-06-03 16:37
@symonk Which version of SeleniumBase are you using?
I'm looking into it, but I need more details. Which OS? Linux? Which browser? Chrome? Firefox?
So far I've found https://stackoverflow.com/questions/43723061/selenium-is-giving-keyerror-sessionid , but that is from 3 years ago, and they weren't using SeleniumBase then.

**Comment by mdmintz** [comment] 2020-06-06 14:56
@symonk Any updates?

**Comment by symonk** [comment] 2020-06-06 18:00
@mdmintz apologies, will get that information as soon as I can

**Comment by mdmintz** [comment] 2020-06-10 03:41
I'm going to close this for now because I can't reproduce this issue on the latest version of SeleniumBase. If it's still happening for you, reopen with the version of SeleniumBase that you're using, the OS, and the browser used. And if you're not using the latest version of SeleniumBase, upgrade to the latest version and try again with that.

**Closed by mdmintz** 2020-06-10 03:41 UTC
