### ISSUE TITLE
Set download folder

### ISSUE THREAD

**Issue by FRIKIdelTO** [seleniumbase/SeleniumBase#2427] opened 2024-01-13 18:00 UTC
How can I define the directory in which the files will be downloaded when interacting with the pages? by default I know it is "downloaded_files" in the current folder, but I want to keep my project folder free of files being downloaded, in fact I would like them to be saved in f'{gettempdir()}/chrome_downloads'. Is this possible?
Thanks for your amazing work!

**Comment by mdmintz** [comment] 2024-01-13 19:39
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1557#issuecomment-1287636878

--------

SeleniumBase creates the ``downloaded_files`` folder in the working directory where ``pytest`` is invoked. Any click-initiated downloads will go there. It's also used for any special files needed. It also holds lock files to prevent issues with multi-threading. The folder resets at the start of every new ``pytest`` run so that past test runs don't interfere with new ones. The folder is hard-coded there to prevent issues. And since the folder is reset at the start of new ``pytest`` runs, you wouldn't want to use any other existing folders for it.

There are lots of built-in test methods that are specially made for that folder, such as:

```python
self.get_downloads_folder()

self.get_browser_downloads_folder()

self.get_path_of_downloaded_file(file)

self.is_downloaded_file_present(file)

self.delete_downloaded_file_if_present(file)
# Duplicates: self.delete_downloaded_file(file)

self.assert_downloaded_file(file)

self.get_downloaded_files(regex=None, browser=False)

self.get_data_from_downloaded_file(file, timeout=None, browser=False)

self.assert_data_in_downloaded_file(data, file, timeout=None, browser=False)
```

If you need files in a different folder, use Python ``os``, ``sys``, and ``shutil`` libraries for copying the files you need into a different folder after they get downloaded to the ``downloaded_files`` folder.

There's also a `pytest` command-line option to archive existing downloads instead of deleting them:
https://github.com/seleniumbase/SeleniumBase/blob/570910c6f6e079cddd00c23e826e202c6489f39e/README.md?plain=1#L673

(A copy of those downloads will go into a folder in the `archived_files/` folder at the end of the `pytest` run.)

**Closed by mdmintz** 2024-01-13 19:39 UTC
Labels: duplicate, question

**Comment by FRIKIdelTO** [comment] 2024-01-13 19:59
I don't use pytest or multithreading, in fact I just migrated to seleniumbase because I had issues with undetected_chromedriver. I just need to be able to configure where I want to save my downloads

**Comment by mdmintz** [comment] 2024-01-13 20:16
If you need files in a different folder, use Python ``os``, ``sys``, and ``shutil`` libraries for copying the files you need into a different folder after they get downloaded to the ``downloaded_files`` folder.

**Comment by Jonathynlee** [comment] 2024-03-05 01:06
@mdmintz I am running this in a lambda and only the tmp folder is writable. There is no way around it. How would I direct the downloads there?

**Comment by FRIKIdelTO** [comment] 2024-03-11 07:51
> @mdmintz I am running this in a lambda and only the tmp folder is writable. There is no way around it. How would I direct the downloads there?

I did like this:

def set_download_dir(driver, down_path):
    driver.command_executor._commands["send_command"] = ("POST", '/session/$sessionId/chromium/send_command')
    params = {
        'cmd': 'Page.setDownloadBehavior',
        'params': {
            'behavior': 'allow',
            'downloadPath': os.path.normpath(os.path.abspath(down_path))
            }
        }
    driver.execute("send_command", params)

**Comment by noahfaro** [comment] 2024-12-26 18:00
I understand that this is a hardcoded folder for a reason, but certain environments (like Lambda as @Jonathynlee mentioned) are read-only except for specific directories, making your response @mdmintz insufficient. This is an actual issue with this repository that prevents us from using it at scale, and would like to hear your thoughts as to why the users cannot be the ones to designate the hardcoded folder that you use. For example, if we could set the DOWNLOADS_FOLDER inside of fixtures.constants.Files, that would already solve the issue at hand.

I am currently trying to implement a workaround where I am quite literally overwriting os commands that point to "downloaded_files" to instead point to "tmp/downloaded_files" so that I can actually deploy this in serverless environments like Lambda, which is certainly (ideally) unnecessary.

**Comment by mdmintz** [comment] 2024-12-26 18:11
Nothing really prevents people from importing `constants` and overriding variables at the start of people's scripts:
https://github.com/seleniumbase/SeleniumBase/blob/35dcd8214325a9b54c1d8ab67eb6f26544c2266c/seleniumbase/fixtures/constants.py#L81

**Comment by gary-conlon** [comment] 2025-03-18 07:45
@mdmintz It is possible to import and set DOWNLOADS_FOLDER. But I am running into the issue when using a dynamic grid. Selenium now has managed downloads which when turned on allow you to talk to the API which will pull the downloads from folders named off session.

https://www.selenium.dev/documentation/grid/configuration/cli_options/#enabling-managed-downloads-by-the-node

Since Seleniumbase has the path hard set here with no option to turn that off, I cannot get back that behaviour that Selenium provided that I need for the grid.

https://github.com/seleniumbase/SeleniumBase/blob/b1b1deec2c0abd274406d8887f2f351e6ea3a187/seleniumbase/core/browser_launcher.py#L2082
