### ISSUE TITLE
Now detected by google email signup

### ISSUE THREAD

**Issue by taytanqbpass** [seleniumbase/SeleniumBase#2262] opened 2023-11-10 21:43 UTC
![image](https://github.com/seleniumbase/SeleniumBase/assets/72385265/3b467c61-082c-42f0-a4c8-af965a201aff)

Version: seleniumbase-4.21.1
Code Setup:
`from seleniumbase import Driver 
driver = Driver(undetected=True,headless=False)
driver.get('https://accounts.google.com/')
`

**Comment by mdmintz** [comment] 2023-11-10 22:51
Duplicate of https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1054

**Closed by mdmintz** 2023-11-10 22:51 UTC
Labels: duplicate, UC Mode

**Comment by mdmintz** [comment] 2023-11-10 23:53
Also, although we're OK with people using automation to log into their own Gmail accounts, we're not OK with people using automation to create new Gmail accounts.

There are lots of valid reasons for using automation for logging into **existing** Gmail accounts. Recently, Google announced that they will deactivate accounts that have been inactive for 2 years: https://support.google.com/accounts/answer/12418290 - Logging into a Gmail account resets the 2-year inactivity clock.

There are several reasons why someone might not log into their Gmail account for more than 2 years:
* They are an astronaut: https://www.nasa.gov/international-space-station/space-station-astronaut-record-holders/
* They are a prisoner-of-war (Eg. https://en.wikipedia.org/wiki/John_McCain)
* They go to college and only use their college email account until they graduate.
* And many more valid reasons!
