### ISSUE TITLE
How to set login to run before executing entire test class

### ISSUE THREAD

**Issue by chenhaijun02** [seleniumbase/SeleniumBase#2510] opened 2024-02-18 01:41 UTC
Hello,Michael:
    I place the login to run before the entire test class is executed. An error will be reported when running. What should I do? Thank you.

`class MyTestClass(BaseCase):

    @classmethod
    def setUpClass(cls):
        super(MyTestClass, cls).setUpClass()
        cls.open("https://www.baidu.com")

Error message:
cls = <class 'demo2.MyTestClass'>

    @classmethod
    def setUpClass(cls):
        super(MyTestClass, cls).setUpClass()
>       cls.open("https://www.baidu.com")
E       TypeError: BaseCase.open() missing 1 required positional argument: 'url'

`

**Comment by mdmintz** [comment] 2024-02-18 04:05
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1243
Have the first test log in, and then reuse the browser session so that you can stay logged in. (``--rs`` / ``--rcs``)

Or follow the model from [examples/boilerplates/base_test_case.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py) where you create a custom class with a custom `setUp()` method that runs before each test.

**Closed by mdmintz** 2024-02-18 04:05 UTC
Labels: duplicate, question
