### ISSUE TITLE
How to change to webDriver":false , for bypassing ? 

### ISSUE THREAD

**Issue by ngantsung** [seleniumbase/SeleniumBase#1933] opened 2023-07-01 07:20 UTC
`with SB(uc_cdp_events=True) as sb: `
       ` sb.open('https://bot.sannysoft.com/') `

There are these element 
 "webDriver": true,
 "webDriverValue": false,

my question is 
how to change to webDriver":false ,

**Comment by mdmintz** [comment] 2023-07-01 12:53
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1925, see https://github.com/seleniumbase/SeleniumBase/issues/1925#issuecomment-1607657563

**Closed by mdmintz** 2023-07-01 12:53 UTC
Labels: duplicate
