### ISSUE TITLE
ActionChains Support

### ISSUE THREAD

**Issue by PankajSavaliya** [seleniumbase/SeleniumBase#2902] opened 2024-07-04 06:43 UTC
```
 action_chains = ActionChains(driver)
                        action_chains.key_down(Keys.CONTROL).key_up(Keys.CONTROL).perform()
```

Do I need to use this above or does any SB has for this method? 

there are a lot of actions that are needed its just a sample.

**Comment by mdmintz** [comment] 2024-07-04 10:46
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2749#discussioncomment-9313866

With SeleniumBase, you can use any raw Selenium method via `sb.driver`.
(That includes the use of `ActionChains`.)

Here's an advanced example: https://github.com/seleniumbase/SeleniumBase/issues/2471#issuecomment-1931316762

**Closed by mdmintz** 2024-07-04 10:46 UTC
Labels: duplicate, question
