### ISSUE TITLE
webdriver classes conflict on enable `uc` and `wire`

### ISSUE THREAD

**Issue by d3cryptofc** [seleniumbase/SeleniumBase#2337] opened 2023-12-04 14:46 UTC
I need to use `wire` mode and `uc` too, but...

**✅ It works**
```python
>>> driver = Driver(wire=True)
>>> driver.requests
[]
```

**❌ It causes a webdriver class conflict**
```python
>>> driver = Driver(wire=True, uc=True)
>>> driver.requests
AttributeError: 'Chrome' object has no attribute 'requests'
```

**Comment by mdmintz** [comment] 2023-12-04 15:08
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2243#issuecomment-1797864769, https://github.com/seleniumbase/SeleniumBase/issues/1774#issuecomment-1444399269, https://github.com/seleniumbase/SeleniumBase/issues/2032#issuecomment-1693931853, https://github.com/seleniumbase/SeleniumBase/issues/2151#issuecomment-1741234068, etc.

Due to unresolved issues with ``selenium-wire``: https://github.com/wkeeling/selenium-wire/search?q=undetected&type=issues, UC Mode and Wire Mode cannot be combined. Pick one or the other.

**Closed by mdmintz** 2023-12-04 15:08 UTC
Labels: duplicate, UC Mode

**Comment by uesleivsouza** [comment] 2024-01-25 16:44
> I need to use `wire` mode and `uc` too, but...
> 
> **✅ It works**
> 
> ```python
> >>> driver = Driver(wire=True)
> >>> driver.requests
> []
> ```
> 
> **❌ It causes a webdriver class conflict**
> 
> ```python
> >>> driver = Driver(wire=True, uc=True)
> >>> driver.requests
> AttributeError: 'Chrome' object has no attribute 'requests'
> ```

Did you find a way to make both work together? I am facing the same situation now.

**Comment by mdmintz** [comment] 2024-01-25 18:06
https://github.com/seleniumbase/SeleniumBase/issues/2337#issuecomment-1838843884 still holds.

The best alternative involves getting the requests from CDP events.
(See [SeleniumBase/examples/uc_cdp_events.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py) for details.)

**Comment by d3cryptofc** [comment] 2024-01-25 18:17
@uesleivsouza 
> Did you find a way to make both work together? I am facing the same situation now.

I didn't, infortunely.. also the CDP events doesn't have a HTTP response text, I needed it 😢

**Comment by mdmintz** [comment] 2024-01-25 20:38
There’s also https://github.com/seleniumbase/SeleniumBase/issues/2220

**Comment by uesleivsouza** [comment] 2024-01-25 22:11
> [#2337 (comment)](https://github.com/seleniumbase/SeleniumBase/issues/2337#issuecomment-1838843884) still holds.
> 
> The best alternative involves getting the requests from CDP events. (See [SeleniumBase/examples/uc_cdp_events.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py) for details.)

Thank you for reply quickly, but unfortunately I think it can't fit to my application, I need to change the request, not only listen it .. I think I have to find another with external tools like proxy.
