### ISSUE TITLE
How to use proxy with extension

### ISSUE THREAD

**Issue by belalmuhamedd** [seleniumbase/SeleniumBase#2397] opened 2023-12-30 14:06 UTC
i add captchaBot extension to driver but when using proxy (without auth) cant connect to server in extension but in chrome works well  .. how i can make it work ?

`driver = Driver(undetected=True, headed=True, agent=userAgent,
                                extension_dir='./dir', proxy=f'http://{proxy}')`

**Comment by mdmintz** [comment] 2023-12-30 16:55
Possibly a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2247, but it's unclear since you haven't provided any details about your environment, or any stack traces or error messages.

You could also try:

```python
from seleniumbase import SB

with SB(uc=True, xvfb=True, extension_dir="./dir", proxy="server:port") as sb:
    sb.driver.uc_open_with_reconnect(URL, 5)
```

(After filling in the proxy info, URL, and making sure your extension directory is valid.)

And if that didn't work, swap `xvfb=True` with `headless2=True`.

But whatever you do, don't set the user agent yourself in UC Mode. It's automatically set to an agent that won't get you detected.

**Closed by mdmintz** 2023-12-30 16:55 UTC
Labels: duplicate, question, UC Mode
