### ISSUE TITLE
Regarding the infinite loop caused by updating Google

### ISSUE THREAD

**Issue by AitchY-sh** [seleniumbase/SeleniumBase#2009] opened 2023-08-17 16:42 UTC
![X(G6LHH6 DNFXG)C H8`X%D](https://github.com/seleniumbase/SeleniumBase/assets/62641916/14156fe3-7cc4-40d4-bfc8-be062962d21c)

I use jenkins to run the test cases, but after the test, it automatically downloads the chromedriver, I don't know why it keeps not stopping. This also causes my jenkins job to run all the time.

**Comment by mdmintz** [comment] 2023-08-17 17:08
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1966, and that was already resolved in newer versions. Upgrade to the latest version of SeleniumBase, and that should resolve your issue.

(I'm assuming you're not on the latest version. Please include your seleniumbase & Python versions when opening tickets.)

**Closed by mdmintz** 2023-08-17 17:08 UTC
Labels: duplicate, feature or fix already exists
