### ISSUE TITLE
very long wait to open simple webpage via Driver with binary_location

### ISSUE THREAD

**Issue by Marwan0** [seleniumbase/SeleniumBase#2462] opened 2024-01-31 02:50 UTC
when i use Driver and pass binary_location of ChromeDriver.exe , the script hang and take very very long time to do any action , here is the script i use 
`
import os
import sys
import time
from seleniumbase import Driver
from multiprocessing import Pool
import multiprocessing as mp

def get_binary_file_path(relative_path):
    """Get the path to the binary file whether script is run as a script or as an executable."""
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, relative_path)
    else:
        return os.path.join(os.path.abspath("."), relative_path)
    

def test_function(I):

    driver = Driver(binary_location=r"D:\Python\Prime_checker\chrome.exe",headless=False, undetectable=True)
    try:
        driver.get("https://gaming.amazon.com/home")
        time.sleep(3)
        driver.execute_script("window.open('https://www.youtube.com');")
        time.sleep(2)
        driver.switch_to.window(driver.window_handles[0])
        time.sleep(1)
        driver.quit()

    except Exception as e:
        driver.quit()
        print(e)

if __name__ == "__main__":
    mp.freeze_support()
    for i in range(5):
        p = Pool(processes=3)
        p.map(test_function, range(3))
        p.close()
        p.join()
        time.sleep(0.5)
`

**Comment by mdmintz** [comment] 2024-01-31 04:36
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2006#issuecomment-1679789785

Only `pytest` multithreading is supported via `pytest-xdist`.
(In the `pytest` [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md), the driver is automatically quit at the end of each test.)

Other multithreading systems such as `multiprocessing.Pool` are likely to experience issues, such as slowness, poor handling of resources in threads, and other issues.

On top of that, you used the JS `window.open()` method instead of the built-in UC Mode methods for opening a URL, which may lead to issues. The UC Mode methods will automatically handle tab-switching as needed.

The UC Mode methods:

```python
driver.uc_open(url)
driver.uc_open_with_tab(url)
driver.uc_open_with_reconnect(url, reconnect_time=None)
driver.uc_click(selector)
driver.uc_switch_to_frame(frame)
```

If you don't need to bypass bot-detection while opening a URL in UC Mode, use: `driver.default_get(url)`, which loads a URL faster because there's no disconnect time between chromedriver and Chrome.

**Closed by mdmintz** 2024-01-31 04:36 UTC
Labels: duplicate, incorrect usage, UC Mode

**Comment by Marwan0** [comment] 2024-01-31 04:43
The reason of going for that approach is i need to open 4 browsers for the same test and all that will be execute via exe from pyinstaller,  do you have any recommendation or better implementation?
I used Driver because i need to execute throw pure python

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdmintz** [comment] 2024-01-31 04:54
The `SB()` format can also be run with pure Python. (Not just the `Driver()` format.)

A lot of the example tests that use the `BaseCase` pytest format have this special line:

```python
BaseCase.main(__name__, __file__)
```

That triggers `pytest` when the script is run with pure `python`. Maybe it's enough for `pyinstaller` ... maybe not.
