### ISSUE TITLE
use_wire=True, undetected=True doesn't working simultaneously

### ISSUE THREAD

**Issue by juhacz** [seleniumbase/SeleniumBase#2243] opened 2023-11-06 21:29 UTC
I want to use slenium wire and undetected simultaneously in selenium base.
Below is an example program that should inject the "application/vnd.opbox-web.v2+json" header during GET, but it doesn't work. When I remove "undetected=True the program works fine, the header is injected. Am I doing something wrong? If so, please provide an example of a working program. Thank you

```
import seleniumbase

def interceptor(request):
    del request.headers['Accept']
    request.headers['Accept'] = 'application/vnd.opbox-web.v2+json'

driver = seleniumbase.Driver(use_wire=True, undetected=True)

driver.request_interceptor = interceptor
driver.get("https://httpbin.org/headers")
print(driver.get_page_source())
print(driver.requests)
driver.quit()
```

**Comment by mdmintz** [comment] 2023-11-07 05:51
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1774#issuecomment-1444399269, https://github.com/seleniumbase/SeleniumBase/issues/2032#issuecomment-1693931853, https://github.com/seleniumbase/SeleniumBase/issues/2151#issuecomment-1741234068, etc.

Due to unresolved issues with ``selenium-wire``: https://github.com/wkeeling/selenium-wire/search?q=undetected&type=issues, UC Mode and Wire Mode cannot be combined. Pick one or the other.

**Closed by mdmintz** 2023-11-07 05:51 UTC
Labels: duplicate, UC Mode

**Comment by juhacz** [comment] 2023-11-07 08:59
Is it possible to add custom headers to requests in seleniumbase without using selenium-wire?

**Comment by juhacz** [comment] 2023-11-07 11:21
I found way do add custom headers:

driver.execute_cdp_cmd("Network.enable", {})
driver.execute_cdp_cmd("Network.setExtraHTTPHeaders", {"headers": {"Accept": "application/vnd.opbox-web.v2+json"}})

But, the browser adds its own "Accept" headers and it doesn't work. application/vnd.opbox-web.v2+json does not appear in the list with accept headers.

When will I use it
driver.execute_cdp_cmd("Network.setExtraHTTPHeaders", {"headers": {"Accept2": "application/vnd.opbox-web.v2+json"}})
Header Accept2 jest wysyłany.

**Comment by tonywangcn** [comment] 2024-07-27 09:59
Hi @juhacz 
Did U figure out how to make the first one work? Thanks

**Comment by juhacz** [comment] 2024-07-27 10:11
> Hi @juhacz Did U figure out how to make the first one work? Thanks

I changed to https://github.com/kaliiiiiiiii/Selenium-Driverless, there I can get such functionality.

**Comment by tonywangcn** [comment] 2024-07-27 10:39
> > Hi @juhacz Did U figure out how to make the first one work? Thanks
> 
> I changed to https://github.com/kaliiiiiiiii/Selenium-Driverless, there I can get such functionality.

Great thanks, will try it out soon.
