### ISSUE TITLE
Proxy configuration got stuck on chrome profile after being run with it with Seleniumbase

### ISSUE THREAD

**Issue by ZoneLover** [seleniumbase/SeleniumBase#3014] opened 2024-08-11 12:06 UTC
I run a profile with a proxy like the code below:
![Screenshot 2024-08-11 150237](https://github.com/user-attachments/assets/8fa73fcf-3a46-4241-a6b4-6a8ff31551d6)

after I try to run it again without the proxy it shows me that it uses the same old proxy settings:
![image](https://github.com/user-attachments/assets/f9947b3e-c8f7-4dc2-a629-a5e20119798b)
![Screenshot 2024-08-11 150558](https://github.com/user-attachments/assets/ba5840e8-772b-48b3-a4bb-c850a35f797e)

**Comment by mdmintz** [comment] 2024-08-11 13:24
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2596#issuecomment-2000160739 / https://github.com/seleniumbase/SeleniumBase/issues/2432#issuecomment-1892459152 / https://github.com/seleniumbase/SeleniumBase/discussions/2331#discussioncomment-7730581.

If you need multiple profiles, set a different `user_data_dir` for each one that you want. Only the `Default` profile is supported.

If you're setting the `user_data_dir` while using UC Mode, then make sure you read https://github.com/seleniumbase/SeleniumBase/discussions/2118#discussioncomment-7029201 first. (Don't mix a regular `user_data_dir` with one that is used by UC Mode Chrome, as the two formats are not compatible.)

And once you set a proxy for a `user_data_dir` in UC Mode, you may have to use that same proxy if you're using that same `user_data_dir`. Use multiple user-data-dir folders if you need to use multiple proxies.

**Closed by mdmintz** 2024-08-11 13:24 UTC
Labels: duplicate, incorrect usage, UC Mode
