### ISSUE TITLE
How to connect to an open browser?

### ISSUE THREAD

**Issue by radovs3245** [seleniumbase/SeleniumBase#2994] opened 2024-08-05 07:09 UTC
Hello.
I didn’t find a specific answer in the topics, can you still connect to an existing browser via 127.0.0.1:port or ws://127.0.0.1:27869/devtools/browser/5c39ae97-e11f-46da-9186-ff6d34ee022b?
I tried this with SB(uc=True, chromium_arg=f"remote-debugging-port=127.0.0.1:{port}") as sb:
and with SB(uc=True, chromium_arg=remote-debugging-port="ws://127.0.0.1:27869/devtools/browser/5c39ae97-e11f-46da-9186-ff6d34ee022b") as sb:
It opens its browser, but does not connect to the open one.
Please give an example of how to connect.

**Comment by mdmintz** [comment] 2024-08-05 07:38
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2983#issuecomment-2263550191

**Closed by mdmintz** 2024-08-05 07:38 UTC
Labels: duplicate, UC Mode
