### ISSUE TITLE
incognito and guest mode stop working when using proxy

### ISSUE THREAD

**Issue by nevoomer** [seleniumbase/SeleniumBase#2475] opened 2024-02-08 16:00 UTC
if proxy is defined, incognito and guest mode are being ignored

**Comment by mdmintz** [comment] 2024-02-08 17:13
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2336#issuecomment-1837716219

--------

As mentioned in https://support.google.com/chrome_webstore/answer/2664769?hl=en -->

“Important: You can't add extensions when you browse in Incognito mode or as a guest.”

Proxy with auth requires the use of a Chrome extension to configure proxy settings. When you set SeleniumBase to use both an extension and incognito mode, it prioritizes the extension.

**Closed by mdmintz** 2024-02-08 17:13 UTC
Labels: duplicate
