### ISSUE TITLE
unsupported command-line flag: --disable-setuid-sandbox

### ISSUE THREAD

**Issue by ScottCov** [seleniumbase/SeleniumBase#3102] opened 2024-09-06 17:38 UTC
```
from seleniumbase import Driver
driver=Driver(uc=True,headed=True)
driver.get('https://www.google.com/')
```

Giving me the following message on Chrome browser (Version 128.0.6613.119 (Official Build) (64-bit)):
Debian 12
Python 3.10.8
seleniumbase 4.30.3

![image](https://github.com/user-attachments/assets/5563d07e-f196-4390-854f-65cf4c079a46)

Is this normal/expected?

Scott

**Comment by mdmintz** [comment] 2024-09-06 17:52
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2270#issuecomment-1808289456

----

`--disable-setuid-sandbox` is an option used for UC Mode on Linux. The warning message itself is harmless. There's a command-line option that removes such warnings, but using it would lead to detection, so having the warning message is better than the alternative.

You can see how commonly it was used with the original undetected-chromedriver:

https://github.com/search?q=repo%3Aultrafunkamsterdam%2Fundetected-chromedriver+disable-setuid-sandbox&type=issues

There's more info on that option in the Chromium documentation:

https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md

Using that option prevented some issues on Linux, so it's there. I don't know all the specifics about it.

**Closed by mdmintz** 2024-09-06 17:52 UTC
Labels: duplicate, UC Mode
