### ISSUE TITLE
[Request] Multiple or condition wait tuple

### ISSUE THREAD

**Issue by boludoz** [seleniumbase/SeleniumBase#2351] opened 2023-12-08 20:06 UTC
Taking advantage of the fact that it is an extra layer of Selenium, I would like to include a condition to wait for the first element found.

I would like to see this feature but well applied and there is no need to specify what element it is (I would like it to be automatic like here, as is the case with seleniumbase). I think it would be extremely useful, especially if it returned the element in question.

Basic concept:
```
class WaitForOrClickableElement:
    def __init__(self, driver, locators, timeout=20, poll_frequency=0.5):
        self.driver = driver
        self.locators = locators
        self.wait_time = timeout
        self.poll_frequency = poll_frequency
        self.element, self.locator = self._wait_for_clickable_element()

    def _wait_for_clickable_element(self):
        end_time = time.time() + self.wait_time
        try:
            sub_wait_time = self.wait_time / len(self.locators)
        except ZeroDivisionError:
            sub_wait_time = self.wait_time

        while True:
            for locator in self.locators:
                try:
                    wait = WebDriverWait(self.driver, timeout=sub_wait_time, poll_frequency=self.poll_frequency)
                    element = wait.until(EC.element_to_be_clickable(locator))
                    return element, locator[1]
                except TimeoutException:
                    if time.time() > end_time:
                        raise Exception("Neither element was clickable after waiting for the specified time")
                except:
                    raise

```

```
element = WaitForOrClickableElement(driver, ((By.XPATH, '//*[@id="auth_email"]'), (By.XPATH, '//*[@id="other"]')))
            if '//*[@id="other"]' in element.locator:
                ....
```

Unfortunately it is not possible to do this with native selenium using a single function.

**Comment by mdmintz** [comment] 2023-12-08 20:32
Looks like a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2342#issuecomment-1841936306

For you case, you could do:

```python
import time

max_wait = time.time() + 20
while True:
    if self.is_element_clickable("selector_1"):
        return self.wait_for_element_clickable("selector_1", timeout=0.1)
    elif self.is_element_clickable("selector_2"):
        return self.wait_for_element_clickable("selector_2", timeout=0.1)
    elif time.time() >= max_wait:
        raise Exception("Neither element was clickable after waiting for the specified time!")
    time.sleep(0.1)
```

Do to the highly specialized manor of this method, it's best that it be added separately to your framework, rather than as part of SeleniumBase. For example, you can create a subclass of BaseCase, add your custom method there, and then have your test classes inherit that subclass, such as in [SeleniumBase/examples/boilerplates/base_test_case.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py)

**Closed by mdmintz** 2023-12-08 20:32 UTC
Labels: duplicate, question

**Comment by boludoz** [comment] 2023-12-08 21:04
> ```python
> wait_for_element_clickable
> ```

Thank you very much for your work.

**Comment by boludoz** [comment] 2023-12-16 20:39
`AttributeError: 'bot_selenium' object has no attribute 'is_element_clickable'`
