### ISSUE TITLE
Cookie add problem

### ISSUE THREAD

**Issue by curl2** [seleniumbase/SeleniumBase#2629] opened 2024-03-21 19:39 UTC
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\REG\main.py", line 55, in setup_ava
    driver.add_cookie ({ 'name' : 'api_token', 'value' : 'token'})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 637, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=123.0.6312.59)
Stacktrace:
        GetHandleVerifier [0x00007FF62D2A8EF2+54786]
        (No symbol) [0x00007FF62D215612]
        (No symbol) [0x00007FF62D0CA64B]
        (No symbol) [0x00007FF62D0CEEC1]
        (No symbol) [0x00007FF62D0D115F]
        (No symbol) [0x00007FF62D0D1250]
        (No symbol) [0x00007FF62D14723C]
        (No symbol) [0x00007FF62D155DE9]
        (No symbol) [0x00007FF62D12BE6A]
        (No symbol) [0x00007FF62D144D02]
        (No symbol) [0x00007FF62D12BC43]
        (No symbol) [0x00007FF62D100941]
        (No symbol) [0x00007FF62D101B84]
        GetHandleVerifier [0x00007FF62D5F7F52+3524194]
        GetHandleVerifier [0x00007FF62D64D800+3874576]
        GetHandleVerifier [0x00007FF62D645D7F+3843215]
        GetHandleVerifier [0x00007FF62D345086+694166]
        (No symbol) [0x00007FF62D220A88]
        (No symbol) [0x00007FF62D21CA94]
        (No symbol) [0x00007FF62D21CBC2]
        (No symbol) [0x00007FF62D20CC83]
        BaseThreadInitThunk [0x00007FFFC45D7E94+20]
        RtlUserThreadStart [0x00007FFFC73F7AD1+33]
``` Python
def setup_ava(token,nick):
    for i in range(3):
        try:
            proxies = open("proxy.txt").read().split("\n")
            prx = random.choice(proxies)
            sett = json.loads(open("settings.txt").read())
            driver = Driver(uc=True,proxy = prx)
            driver.get("https://twitch.tv")
            driver.add_cookie ({ 'name' : 'api_token', 'value' : '2cc3a27a02dfc50ad29062dbc670133e'})
            driver.add_cookie ({ 'name' : 'auth-token', 'value' : token})
            driver.get(f"https://www.twitch.tv/settings/profile")
            time.sleep(2)
            match_using_text = driver.find_element(By.XPATH, "//input[@type='file']").send_keys("C:/avatarka.jpg")
            time.sleep(6)
            match_using_text = driver.find_element(By.XPATH, "//button[@class='ScCoreButton-sc-ocjdkq-0 ScCoreButtonPrimary-sc-ocjdkq-1 bTXTVH gmCwLG']").click()
            
            element = WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.XPATH, "//div[@class='ScNotificationFigure-sc-1984gyo-0 lofsQO tw-notification-figure']")))
            time.sleep(2)
            driver.quit()
            return 200
        except:
            print(traceback.format_exc())
    return 404
```

Problem seems only in uc mode

**Comment by mdmintz** [comment] 2024-03-21 20:15
Duplicate of: https://stackoverflow.com/a/35551303/7058266

Also see: https://github.com/SeleniumHQ/selenium/issues/12083#issuecomment-1557892033

**Closed by mdmintz** 2024-03-21 20:15 UTC
Labels: external

**Comment by curl2** [comment] 2024-03-22 18:50
It didn't help
I still get error:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\REG\main.py", line 56, in setup_ava
    driver.add_cookie ({ 'name' : 'api_token', 'value' : '2cc3a27a02dfc50ad29062dbc670133e','path':'/'})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 637, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=123.0.6312.59)
Stacktrace:
        GetHandleVerifier [0x00007FF62D2A8EF2+54786]
        (No symbol) [0x00007FF62D215612]
        (No symbol) [0x00007FF62D0CA64B]
        (No symbol) [0x00007FF62D0CEEC1]
        (No symbol) [0x00007FF62D0D115F]
        (No symbol) [0x00007FF62D0D1250]
        (No symbol) [0x00007FF62D14723C]
        (No symbol) [0x00007FF62D155DE9]
        (No symbol) [0x00007FF62D12BE6A]
        (No symbol) [0x00007FF62D144D02]
        (No symbol) [0x00007FF62D12BC43]
        (No symbol) [0x00007FF62D100941]
        (No symbol) [0x00007FF62D101B84]
        GetHandleVerifier [0x00007FF62D5F7F52+3524194]
        GetHandleVerifier [0x00007FF62D64D800+3874576]
        GetHandleVerifier [0x00007FF62D645D7F+3843215]
        GetHandleVerifier [0x00007FF62D345086+694166]
        (No symbol) [0x00007FF62D220A88]
        (No symbol) [0x00007FF62D21CA94]
        (No symbol) [0x00007FF62D21CBC2]
        (No symbol) [0x00007FF62D20CC83]
        BaseThreadInitThunk [0x00007FFFC45D7E94+20]
        RtlUserThreadStart [0x00007FFFC73F7AD1+33]
        
```Python
def setup_ava(token,nick):
    for i in range(3):
        try:
            proxies = open("proxy.txt").read().split("\n")
            prx = random.choice(proxies)
            sett = json.loads(open("settings.txt").read())
            driver = Driver(uc=True,proxy = prx)#,headless=True)
            driver.get("https://twitch.tv")
            time.sleep(3)
            driver.add_cookie ({ 'name' : 'api_token', 'value' : '2cc3a27a02dfc50ad29062dbc670133e','path':'/'})
            driver.add_cookie ({ 'name' : 'auth-token', 'value' : token,'path':'/'})
            driver.get(f"https://www.twitch.tv/settings/profile")
            time.sleep(2)
            match_using_text = driver.find_element(By.XPATH, "//input[@type='file']").send_keys("C:/avatarka.jpg")
            time.sleep(6)
            match_using_text = driver.find_element(By.XPATH, "//button[@class='ScCoreButton-sc-ocjdkq-0 ScCoreButtonPrimary-sc-ocjdkq-1 bTXTVH gmCwLG']").click()
            
            element = WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.XPATH, "//div[@class='ScNotificationFigure-sc-1984gyo-0 lofsQO tw-notification-figure']")))
            time.sleep(2)
            driver.quit()
            return 200
        except:
            print(traceback.format_exc())
            print("Аву установить не удалось! :(")
    return 404
```

I get this error on uc chrome 123 version, on more old version all be good

**Comment by mdmintz** [comment] 2024-03-22 19:01
Not sure, but I saw several issues today related specifically to Chrome / Chromedriver 123, such as https://bugs.chromium.org/p/chromedriver/issues/detail?id=4743 (unrelated).
The error isn't coming from SeleniumBase, so I'm not sure how to help.
