### ISSUE TITLE
Proxies Detected Using PixelScan

### ISSUE THREAD

**Issue by mdonova33** [seleniumbase/SeleniumBase#1729] opened 2023-02-03 05:35 UTC
Recently, the uc mode has been failing Cloudflare "turnstile" checks, when a proxy is in use. The reason seems to be related to using a proxy, as now proxies are detected in use on PixelScan.

**Comment by mdmintz** [comment] 2023-02-03 06:28
We're aware of the situation. This is a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1725
A new release will be shipped soon.

**Closed** 2023-02-03 07:09 UTC
Labels: duplicate

**Comment by mdmintz** [comment] 2023-02-04 17:11
More improvements to UC Mode in ``4.12.5`` - https://github.com/seleniumbase/SeleniumBase/issues/1725#issuecomment-1416661834

**Comment by iamumairayub** [comment] 2023-11-25 08:00
Hey @mdmintz 

I am running latest SB with proxies and I cannot pass the proxy test.

![image](https://github.com/seleniumbase/SeleniumBase/assets/13570295/d2ba2911-cf24-4164-8ac9-f0cb030ac68e)

```
driver = Driver(
    uc=True, 
    headless=False,
    binary_location=r'/bin/google-chrome',
    proxy='http://my-proxy:10000',
)
driver.uc_open_with_reconnect("https://pixelscan.net/", reconnect_time=60)
```

They are still able to see my real IP.

**Comment by mdmintz** [comment] 2023-11-25 09:50
@iamumairayub See https://github.com/seleniumbase/SeleniumBase/discussions/2276#discussioncomment-7560755

**Comment by iamumairayub** [comment] 2023-11-25 14:37
ok understood that UC does not hide your real IP, there still a way for pixelscan or any other anti-bot technology to detect your real IP.
Is it because then my proxy provider makes request to target website it sends some headers to target website to reveal my real IP/location?
@mdmintz can you suggest me how do I completely hide my real IP? Any recommendation?

**Comment by mdmintz** [comment] 2023-11-27 03:38
@iamumairayub That's probably dependent on your proxy server.
