### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222

### ISSUE THREAD

**Issue by iamumairayub** [seleniumbase/SeleniumBase#2314] opened 2023-11-24 10:21 UTC
I have had SB (SeleniumBase) working pretty well with UC mode (without any virtualdisplay/xvfb) and I was getting an error ["You are using a Chromium-based browser"](https://github.com/seleniumbase/SeleniumBase/discussions/2311) when testing with https://pixelscan.net

So I decided to run command `sudo snap remove chromium` and then I started getting error 

`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222`

Here is my most basic code, it works well with `uc=False` but it is not what I want.

```
options = Options()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = Driver(
    uc=True,
    headless=True,
    cap_string=options.to_capabilities(),
)
driver.uc_open_with_reconnect("https://pixelscan.net/", reconnect_time=10)
```

Tried commenting our `cap_string`
Tried `sudo snap install chromium`
Tried uninstalling and installing `undetected_chromedriver` again
Tried uninstalling and installing `seleniumbase` again

I saw an issue on [SB issues](https://github.com/seleniumbase/SeleniumBase/issues) and also on https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues but those solutions/workarounds did not help.

```
Distributor ID: Ubuntu
Description: Ubuntu 20.04.5 LTS
Release: 20.04
Codename: focal

google-chrome --version
Google Chrome 119.0.6045.159

Python 3.10.7

seleniumbase.version
'4.21.4'
```

**Comment by mdmintz** [comment] 2023-11-24 10:44
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2030#issuecomment-1693345122

--------

Or if you need to use the `Driver()` format, then use https://github.com/mdmintz/sbVirtualDisplay for Xvfb activation:

```python
from sbvirtualdisplay import Display
from seleniumbase import Driver

display = Display(visible=0, size=(1440, 1880))
display.start()

driver = Driver(uc=True, headless=True)
driver.uc_open_with_reconnect("https://pixelscan.net/", reconnect_time=10)
# ...
driver.quit()

display.stop()
```

**Closed by mdmintz** 2023-11-24 10:44 UTC
Labels: duplicate, external, UC Mode
