### ISSUE TITLE
Don't work pageLoadStrategy

### ISSUE THREAD

**Issue by Dourfyt** [seleniumbase/SeleniumBase#3142] opened 2024-09-18 10:08 UTC
I use this construction

    chrome_args = [
        "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
        f"--proxy-server=http://{proxy}",
        "--ignore-certificate-errors",
        "--ignore-ssl-errors",
        "--block-images",
        "--headless",
        "--disable-gpu",
        "--no-sandbox",
        "--disable-dev-shm-usage"
    ]
wtih SB(uc=True, headed=False, headless=True, page_load_strategy="none", block_images=True, proxy=proxy, chromium_arg=chrome_args, skip_js_waits=True) as driver:

when I call driver.open(url), it waits for the page and the images on it to be fully loaded, despite page_load_strategy="none" and block_images=True

**Comment by mdmintz** [comment] 2024-09-18 14:02
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/3038#discussioncomment-10408536.

----

It looks like you're trying to set some args that have already been set by default, (such as `--disable-dev-shm-usage`, `--ignore-certificate-errors`, `--disable-gpu`, etc.), or args that already have a variable assigned to them (Eg. `--agent="AGENT"`, `--proxy="user:pass@ip:port"`, etc): 

https://github.com/seleniumbase/SeleniumBase/blob/2aa5abe9b84f633fc5a7610e0c735b4d806d6769/seleniumbase/core/browser_launcher.py#L1850

https://github.com/seleniumbase/SeleniumBase/blob/2aa5abe9b84f633fc5a7610e0c735b4d806d6769/seleniumbase/core/browser_launcher.py#L1821

https://github.com/seleniumbase/SeleniumBase/blob/2aa5abe9b84f633fc5a7610e0c735b4d806d6769/seleniumbase/core/browser_launcher.py#L1845

https://github.com/seleniumbase/SeleniumBase/blob/2aa5abe9b84f633fc5a7610e0c735b4d806d6769/seleniumbase/core/browser_launcher.py#L1895

https://github.com/seleniumbase/SeleniumBase/blob/2aa5abe9b84f633fc5a7610e0c735b4d806d6769/seleniumbase/core/browser_launcher.py#L1437


The built-in args take priority over anything set in `chromium_arg`, in the case of duplicates. Setting the same arg twice may also cause issues. (Check [seleniumbase/core/browser_launcher.py](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/browser_launcher.py) to see what already exists.) **`chromium_arg` takes a comma-separated string (not a list).** Note that SeleniumBase already sets most args that you need for you. (This isn't like other frameworks where you manually have to set important options.

Also, some args that you're trying to set will prevent UC Mode from working at all, such as `--headless`. (UC Mode won't work in headless mode because it uses `PyAutoGUI` to click on some things, like CAPTCHAs.) Blocking images can get you detected. Changing the default User Agent can get you detected (UC Mode gives you a good one by default.)

Changing the `page_load_strategy` may cause problems if you're not waiting as needed in some areas.

**Closed by mdmintz** 2024-09-18 14:02 UTC
Labels: duplicate, invalid usage, UC Mode
