### ISSUE TITLE
 open a Chrome profile using seleniumbase

### ISSUE THREAD

**Issue by subh-sk** [seleniumbase/SeleniumBase#2487] opened 2024-02-12 19:53 UTC
Hi @mdmintz
I am trying to open a Chrome profile using seleniumbase but am not able to find any documents related to it. Please help me with it.

Currently, I have tried the below method, but it didn't open my Chrome profile.

```
with SB(uc=True, user_data_dir=r'C:\Users\username\AppData\Local\Google\Chrome\User Data\Default') as sb:
    sb.driver.get('https://google.com')
```
the above code didn't open my profile
Can you please tell me what the correct code is? Please help me out. With the correct code, how can I open my Chrome profile? or any alternative method?

**Comment by mdmintz** [comment] 2024-02-12 20:02
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2432#issuecomment-1892459152 / https://github.com/seleniumbase/SeleniumBase/discussions/2331#discussioncomment-7730581

If you need multiple profiles, set a different `user_data_dir` for each one that you want. Only the `Default` profile is supported.

If you're setting the `user_data_dir` while using UC Mode, then make sure you read https://github.com/seleniumbase/SeleniumBase/discussions/2118#discussioncomment-7029201 first. (Don't mix a regular `user_data_dir` with one that is used by UC Mode Chrome, as the two formats are not compatible.)

**Closed by mdmintz** 2024-02-12 20:02 UTC
Labels: duplicate, question, UC Mode

**Comment by subh-sk** [comment] 2024-02-13 07:16
I'm using Windows, and `'C:\Users\username\AppData\Local\Google\Chrome\User Data\Default` has a blank space in the path, so I can't use it. If I can, what's the best way to achieve it? even the code is  not opening my default profile can you please help me how I can set `user_data_dir` with `UC` if possible?

**Comment by mdmintz** [comment] 2024-02-13 10:09
Create your `user_data_dir` relative to where you run your scripts, eg:

```python
with SB(uc=True, user_data_dir="user_data_dir") as sb:
    sb.driver.get('https://google.com')
```

A UC Mode user_data_dir isn't compatible with a regular Chrome user_data_dir anyway, so it should be kept separate. (Also, you had pointed your previous user_data_dir at a profile directory. They are not the same. The profile directory lives inside the user_data_dir, and only the "Default" profile is supported.)
