### ISSUE TITLE
How to connect seleniumbase.Driver to "debugger_address"

### ISSUE THREAD

**Issue by henzycuong1** [seleniumbase/SeleniumBase#2396] opened 2023-12-29 05:58 UTC
Someone can help me connect seleneniumbase.Driver to a existing driver with "debugger_address" and "chromedriver" was patched. I tried some code below

Example 1:
```
from seleniumbase.undetected import Chrome, ChromeOptions
remote_debugging_address = "127.0.0.1:5555"
options = ChromeOptions()
options.debugger_address = remote_debugging_address
driver = Chrome(options=options, 
                driver_executable_path=driver_path, 
                patch_driver=False)
driver.get('https://www.google.com/')
input("WAIT")
```
Example 2:
```
from seleniumbase import Driver
remote_debugging_address = "127.0.0.1:5555"
driver = Driver(browser='chrome',chromium_arg=f'remote-debugging-port={remote_debugging_address.split(":")[-1]},remote-debugging-host={remote_debugging_address.split(":")[0]}')
driver.get('https://www.google.com/')
input("WAIT")
```
it works but opens another launcher.

Example 3 (worked fine but core selenium):
```
from selenium import webdriver
from seleniumbase.undetected import  ChromeOptions
from selenium.webdriver.chrome.service import Service
remote_debugging_address = "127.0.0.1:5555"
browser_location = "PATH_TO_CHROME_EXE"
driver_path = "PATH_TO_CHROMEDRIVER"
options = ChromeOptions()
options.debugger_address = remote_debugging_address 
options.binary_location = browser_location 
service = Service(executable_path=driver_path )
driver = webdriver.Chrome(options=options,service=service)
driver.get('https://www.google.com/')
input("WAIT")
```

**Comment by mdmintz** [comment] 2023-12-29 17:56
This is a duplicate of these two tickets:

* https://github.com/seleniumbase/SeleniumBase/issues/2369#issuecomment-1858989224

* https://github.com/seleniumbase/SeleniumBase/issues/2225#issuecomment-1785326861

**Closed by mdmintz** 2023-12-29 17:56 UTC
Labels: duplicate, question, UC Mode
