### ISSUE TITLE
Ubuntu Linux error while running my_first_test.py 

### ISSUE THREAD

**Issue by dwk601** [seleniumbase/SeleniumBase#2800] opened 2024-05-23 20:36 UTC
```
argparse.ArgumentError: argument --browser: conflicting option string: --browser
```
i just set the env with python and install all requirements and run the pytest and this error shows up

**Comment by mdmintz** [comment] 2024-05-23 23:24
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/976#discussioncomment-1259611

That error occurs when the same ``pytest`` command-line argument is being defined in more than two places. Have you previously installed a framework that has ``--browser`` defined as one of the available options? Or are you trying to define extra arguments in a custom ``conftest.py`` file? You can get around this by installing SeleniumBase in a new virtual environment if you can't figure out where the other definitions are defined. Or if you can find the other location where ``--browser`` is defined, then just remove that definition. If another framework/library has it, ``pip uninstall`` it. Command-line arguments can only be defined once per argument.

Alternatively, use ``pynose`` as a temporary fix to run tests until you've removed the duplicate definition.
Eg. ``pynose my_first_test.py``. (``nosetests`` works the same.)
(That is already included with recent versions of SeleniumBase.)

**Closed by mdmintz** 2024-05-23 23:24 UTC
Labels: duplicate
