### ISSUE TITLE
The driver is downloaded multiple times when using pyinstaller

### ISSUE THREAD

**Issue by NiamurRashid** [seleniumbase/SeleniumBase#3073] opened 2024-08-29 12:37 UTC
Whenever i bundle my script using pyinstaller 
And then run. it downloads chromedriver everytime.

**Comment by mdmintz** [comment] 2024-08-29 12:59
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2046.

`chromedriver` is only downloaded if it doesn't already exist in the `seleniumbase/drivers` folder.
It looks like you've configured `pyinstaller` to generate a new folder every time it runs. (`seleniumbase` doesn't have control over that.) That means it'll keep downloading the driver unless you configure `PyInstaller` to reuse the folder.

If you can't change `PyInstaller` configuration, you can hide those install messages by adding this:

```python
from seleniumbase.config import settings
settings.HIDE_DRIVER_DOWNLOADS = True
```

`PyInstaller` is an external project, so you'll have to figure out how to configure it properly.

**Closed** 2024-08-29 13:01 UTC
Labels: duplicate, external
