### ISSUE TITLE
how to fix the detected in https://bot.sannysoft.com/ ? 

### ISSUE THREAD

**Issue by ngantsung** [seleniumbase/SeleniumBase#1925] opened 2023-06-26 14:46 UTC
![ 上傳螢幕截圖 2023-06-26 at 10.42.45 ![ 上傳螢幕截圖 2023-06-26 at 10.42.55 ![ 上傳螢幕截圖 2023-06-26 at 10.40.31 PM.png...]() PM.png...]（） PM.png...]（） [ 上傳螢幕截圖 2023-06-26 at 10.40.34 PM.png...]() ![ 上傳螢幕截圖 2023-06-26 at 10.4 <img width="1440" alt="Screenshot 2023-06-26 at 10 41 12 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/111569568/6f1774ff-e745-496f-a250-3dee13abc557"> 1.09 PM.png...]()小時

when I use the sb , and i will be detected , but if I use the selenium that is fine , so how to fix it ? Thanks again

**Comment by mdmintz** [comment] 2023-06-26 14:54
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/1912#issuecomment-1589611172

I got the same result when using a regular Chrome browser, so the value there isn't accurate.

But the following script works, so it means anti-detection is working:

```python
from seleniumbase import Driver
import time

driver = Driver(uc_cdp=True, incognito=True)
driver.get("https://antoinevastel.com/bots/datadome")
time.sleep(5)
driver.quit()
```

<img width="1267" alt="Screenshot 2023-06-13 at 12 05 11 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/ec2b532c-8024-441e-9846-ac6506240f91">

**Closed by mdmintz** 2023-06-26 14:54 UTC
Labels: duplicate, question
