### ISSUE TITLE
how can i move the mouse to specific element using SELENIUMBASE

### ISSUE THREAD

**Issue by pythondeveloperz** [seleniumbase/SeleniumBase#2859] opened 2024-06-18 07:27 UTC
> from seleniumbase import SB
> 
> with SB(uc=True)as sb:
>     #url = "https://www.wsj.com/livecoverage/stock-market-today-dow-jones-earnings-05-30-2024?mod=lctimeline_finance_viewall"
>     url = "https://www.google.com"
>     sb.driver.uc_open_with_reconnect(url, 20)
>     text = "expample.online"
>     #for i in text:
>         #sb.send_keys(selector="css selector",text=i, by="#APjFqb")
>         #sb.sleep(0.25)
>     sb.hover(selector="css selector", by="body > div.L3eUgb > div.o3j99.ikrT4e.om7nvf > form > div:nth-child(1) > div.A8SBwf > div.FPdoLc.lJ9FBc > center > input.gNO89b")
>     print(1)
>     #sb.uc_click("body > div.L3eUgb > div.o3j99.ikrT4e.om7nvf > form > div:nth-child(1) > div.A8SBwf > div.FPdoLc.lJ9FBc > center > input.gNO89b")
>     print(0)
> 
>     input()

how can i move the mouse to specific element using SELENIUMBASE

**Comment by mdmintz** [comment] 2024-06-18 15:10
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2749#discussioncomment-9313866

**Closed by mdmintz** 2024-06-18 15:10 UTC
Labels: duplicate, question, UC Mode
